In [1]:
# Librerías para manipulación de datos y scraping
import pandas as pd

# Librerías para manejar el navegador y scraping de Google Maps
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# Librerías para manejar esperas en Selenium
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

print("¡Librerías importadas correctamente!")

¡Librerías importadas correctamente!

In [2]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

print("¡Librerías listas!")

¡Librerías listas!

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# Configuración de Chrome
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")
options.add_argument("--disable-notifications")

# Inicializamos el driver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

print("Driver de Chrome listo")

Driver de Chrome listo

In [5]:
# URL de búsqueda en Google Maps
url = "https://www.google.com/maps/search/fisioterapia+medellin"

# Abrimos la página
driver.get(url)

print("Google Maps abierto con la búsqueda")

Google Maps abierto con la búsqueda

In [6]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

# Espera hasta que aparezcan los resultados
wait = WebDriverWait(driver, 10)
results = wait.until(EC.presence_of_all_elements_located(
    (By.XPATH, '//div[@role="article"]')
))

# Lista para guardar datos
leads = []

# Extraemos nombre y dirección de los primeros 10 resultados como ejemplo
for result in results[:10]:
    try:
        name = result.find_element(By.XPATH, './/h3').text
    except:
        name = ""
    try:
        address = result.find_element(By.XPATH, './/span[contains(@class,"section-result-location")]').text
    except:
        address = ""
    leads.append({"Nombre": name, "Dirección": address})

# Guardamos en un DataFrame
df = pd.DataFrame(leads)
df

  Nombre Dirección
0
1
2
3
4
5
6

In [8]:
import time

# Espera unos segundos para que la página cargue completamente
time.sleep(5)

# Buscamos los resultados visibles
results = driver.find_elements(By.XPATH, '//div[contains(@aria-label,"Resultados de búsqueda")]//div[@role="article"]')

leads = []

for result in results[:10]:  # primeros 10 resultados
    try:
        name = result.find_element(By.XPATH, './/div[@role="heading"]').text
    except:
        name = ""
    try:
        address = result.find_element(By.XPATH, './/span[contains(text(),"Medellín")]').text
    except:
        address = ""
    leads.append({"Nombre": name, "Dirección": address})

# Guardamos en DataFrame
df = pd.DataFrame(leads)
df

Empty DataFrame
Columns: []
Index: []

In [9]:
import googlemaps
import pandas as pd
import time

# Tu API Key
API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"

# Conexión con la API
gmaps = googlemaps.Client(key=API_KEY)

# Lista para guardar todos los leads
leads = []

# Primer búsqueda: centros odontológicos en Medellín
query = "centros odontológicos Medellín"
results = gmaps.places(query=query, type="dentist", language="es")

# Función para extraer detalles de cada lugar
def get_place_details(place_id):
    details = gmaps.place(place_id=place_id, fields=['formatted_phone_number','website'])
    phone = details.get('result', {}).get('formatted_phone_number', '')
    website = details.get('result', {}).get('website', '')
    return phone, website

# Extraer datos de la primera página de resultados
for place in results['results']:
    name = place.get('name', '')
    address = place.get('formatted_address', '')
    rating = place.get('rating', '')
    place_id = place.get('place_id', '')
    
    phone, website = get_place_details(place_id)
    
    leads.append({
        "Nombre": name,
        "Dirección": address,
        "Teléfono": phone,
        "Web": website,
        "Rating": rating
    })

# Guardar en Excel
df = pd.DataFrame(leads)
df.to_excel("leads_odontologos_medellin.xlsx", index=False)

df

ModuleNotFoundError: No module named 'googlemaps'

In [11]:
!pip install googlemaps pandas --upgrade

Requirement already satisfied: googlemaps in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (4.10.0)
Requirement already satisfied: pandas in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.1)
Requirement already satisfied: requests<3.0,>=2.20.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from googlemaps) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2026.2.25)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import sys
print(sys.executable)

C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\python.exe

In [13]:
import googlemaps
import pandas as pd
import time

print("¡Librerías cargadas correctamente!")

¡Librerías cargadas correctamente!

In [15]:
import requests
import pandas as pd
import time

# -----------------------------
# 1️⃣ Tu API Key (Places API Nueva)
# -----------------------------
API_KEY = "TU_API_KEY_AQUI"

# -----------------------------
# 2️⃣ Parámetros de búsqueda
# -----------------------------
query = "centros odontológicos Medellín"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"

leads = []

# -----------------------------
# 3️⃣ Paginación automática
# -----------------------------
params = {
    "query": query,
    "key": API_KEY,
    "language": "es"
}

while True:
    response = requests.get(url_search, params=params)
    data = response.json()
    
    for place in data.get("results", []):
        name = place.get("name", "")
        address = place.get("formatted_address", "")
        rating = place.get("rating", "")
        place_id = place.get("place_id", "")
        
        # Detalles adicionales: teléfono y web
        url_details = "https://maps.googleapis.com/maps/api/place/details/json"
        details_params = {
            "place_id": place_id,
            "fields": "formatted_phone_number,website",
            "key": API_KEY,
            "language": "es"
        }
        details_resp = requests.get(url_details, params=details_params).json()
        phone = details_resp.get("result", {}).get("formatted_phone_number", "")
        website = details_resp.get("result", {}).get("website", "")
        
        leads.append({
            "Nombre": name,
            "Dirección": address,
            "Teléfono": phone,
            "Web": website,
            "Rating": rating
        })
    
    # Revisar si hay más páginas
    next_page_token = data.get("next_page_token")
    if next_page_token:
        time.sleep(2)  # Espera para que Google genere la siguiente página
        params = {"pagetoken": next_page_token, "key": API_KEY, "language": "es"}
    else:
        break

# -----------------------------
# 4️⃣ Guardar en Excel
# -----------------------------
df = pd.DataFrame(leads)
df.to_excel("leads_odontologos_medellin.xlsx", index=False)
df

ModuleNotFoundError: No module named 'openpyxl'

In [16]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [18]:
df.to_excel("leads_odontologos_medellin.xlsx", index=False)

In [19]:
import requests
import pandas as pd

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
query = "centros odontológicos Medellín"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"

params = {
    "query": query,
    "key": API_KEY,
    "language": "es"
}

response = requests.get(url_search, params=params).json()
print("Status:", response.get("status"))
print("Resultados encontrados:", len(response.get("results", [])))

Status: REQUEST_DENIED
Resultados encontrados: 0

In [20]:
import requests
import pandas as pd

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
query = "centros odontológicos Medellín"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"

params = {
    "query": query,
    "key": API_KEY,
    "language": "es"
}

response = requests.get(url_search, params=params).json()
print("Status:", response.get("status"))
print("Resultados encontrados:", len(response.get("results", [])))
```

Debe salir:
```
Status: OK
Resultados encontrados: 20

SyntaxError: invalid syntax (562237009.py, line 17)

In [21]:
import requests
import pandas as pd

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
query = "centros odontológicos Medellín"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"

params = {
    "query": query,
    "key": API_KEY,
    "language": "es"
}

response = requests.get(url_search, params=params).json()
print("Status:", response.get("status"))
print("Resultados encontrados:", len(response.get("results", [])))

Status: OK
Resultados encontrados: 20

In [22]:
import requests
import pandas as pd
import time

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
query = "centros odontológicos Medellín"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"
url_details = "https://maps.googleapis.com/maps/api/place/details/json"

leads = []
params = {"query": query, "key": API_KEY, "language": "es"}

while True:
    response = requests.get(url_search, params=params).json()
    
    for place in response.get("results", []):
        place_id = place.get("place_id", "")
        
        details = requests.get(url_details, params={
            "place_id": place_id,
            "fields": "formatted_phone_number,website",
            "key": API_KEY
        }).json()
        
        leads.append({
            "Nombre": place.get("name", ""),
            "Dirección": place.get("formatted_address", ""),
            "Teléfono": details.get("result", {}).get("formatted_phone_number", ""),
            "Web": details.get("result", {}).get("website", ""),
            "Rating": place.get("rating", "")
        })
        print(f"✅ {place.get('name')}")
    
    next_page_token = response.get("next_page_token")
    if next_page_token:
        time.sleep(3)
        params = {"pagetoken": next_page_token, "key": API_KEY}
    else:
        break

df = pd.DataFrame(leads)
df.to_excel("leads_odontologos_medellin.xlsx", index=False)
print(f"\n✅ Total leads guardados: {len(leads)}")
df

✅ Centro odontológico KMO Smile Especialistas
✅ Premium Dental Medellín
✅ Clínica Dental Home
✅ ORAL CONCEPT INVISALIGN
✅ Odontología la 78 Urgencia las 24 horas
✅ Odontoespecialistas
✅ Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín
✅ Dental Center
✅ Consultorio odontologico la 73
✅ Infinity Smile
✅ Oral Studio
✅ Dentioral - Sede Poblado
✅ Sanadent Odontólogos - La Mejor Clínica Dental en Medellín
✅ CR Dental Studio
✅ Dental Expertos
✅ Royal Dental Care
✅ Bioestética Dental
✅ ORAL MAS ESPECIALISTAS
✅ Odontología 30a
✅ Clínica Viena / Veneers Medellín
✅ Ortounion Clínica Odontológica
✅ Consultorio Odontológico Vida Oral
✅ Centro Odontológico San Martin
✅ URGENCIAS ODONTOLOGICAS, MEDELLÍN
✅ Smile Natural Studio | Clínica & Spa Odontológico
✅ Centro Radiológico Oral Centro de Medellin
✅ DentiOral - Sede Belén
✅ Odontología The Best Smile Centro Medellín
✅ Dra Liliana Gutiérrez L.
✅ Bocas&Risas - Clínica Odontológica en Medellín
✅ Odontoss Centro
✅ Oral Center Poblado
✅ Oral Elite Consultorio Odontológico atendido por el Dr Alejandro Ramírez
✅ Sanadent
✅ Dentilandia Odontología para Niños / Odontopediatria Medellin
✅ Dr. Mauricio Arias - Odontólogo Experto en Medellín English Dentist
✅ Oralimagen
✅ MDental Láser
✅ Clínica Unilaser
✅ Oral + ortodoncia
✅ Odontólogos y Especialistas
✅ Trébol Odontología Especializada Medellín
✅ Clínica Odontológica Oral Laser Centro
✅ Odontología el Poblado - Oral 10 - Diseños de Sonrisa en Medellín
✅ Consultorio odontológico Smiley
✅ Centro Médico Buenos Aires
✅ Odontocer, Centro de Estética y Rehabilitación Oral
✅ CM Odontología
✅ Odontologos en Medellin
✅ Innova Odontologos Especialistas
✅ Focus Dental Center Odontología
✅ Odontopraxis | Odontología Medellín | Odontológos
✅ CENTRO DENTAL LA ESPERANZA
✅ Clinica Odontoser
✅ Dental Specialists Medellín
✅ Ana Virgen Smile
✅ Camila Paredes Odontología
✅ Odontología Especializada Medellín
✅ DentiSalud El Poblado - Clínicas Odontológicas
✅ Clínica Odontológica Visión de las Américas

✅ Total leads guardados: 60

,Nombre,Dirección,Teléfono,Web,Rating
0,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,,4.9
1,Premium Dental Medellín,"Local 2101. CC Premium Plaza, El Poblado, Mede...",320 4010740,http://premiumdentalmedellin.com/,4.9
2,Clínica Dental Home,"Cl. 34 #34A-76 Consultorio 401, Laureles - Est...",310 4194654,https://clinicadentalhome.com/?utm_source=goog...,4.9
3,ORAL CONCEPT INVISALIGN,"Cra. 70 #32 b 51 local 1, Medellín, Belén, Med...",313 7662008,https://oralconcept.co/home/oral-concept,5.0
4,Odontología la 78 Urgencia las 24 horas,"Cl. 45A #77 a 10, Los Pinos, Medellín, Laurele...",312 2478447,https://consultorioodontologicola78.com/,4.3
5,Odontoespecialistas,"Calle 34 ##43-66 Local 1008 1009, Medellín, An...",313 7591236,http://www.odontoespecialistas.com/,5.0
6,Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín,"Cra. 43A #18sur-135 piso 9, oficina 910, El Po...",305 4566979,http://www.dranazuluaga.com/,4.9
7,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9
8,Consultorio odontologico la 73,"AKT Colombia, Cl 44 #73 - 12 segundo piso, Lau...",318 7501226,http://www.odontologosla73.com/,4.9
9,Infinity Smile,"Cra. 78A #34-41, Laureles - Estadio, Medellín,...",323 4650026,https://infinitysmile.com.co/,4.9
10,Oral Studio,"Cl. 19a # 44 - 25 Consultorio 2001, El Poblado...",312 7093687,https://www.oralstudio.com.co/,5.0
11,Dentioral - Sede Poblado,"Cra. 43A #34-95 Local 200, Centro comercial Al...",(604) 4448911,https://dentioral.com/,5.0
12,Sanadent Odontólogos - La Mejor Clínica Dental...,"Av. 33 #· 81 - 17, Laureles - Estadio, Medellí...",(604) 4486126,http://www.sanadentodontologos.com.co/,4.9
13,CR Dental Studio,"sector Las Lomas Edificio C13, Cra. 32 #13-49 ...",302 3291500,https://www.instagram.com/crdentalstudio/,5.0
14,Dental Expertos,"Cra. 52 # 7-115, Guayabal, Medellín, Guayabal,...",300 8938020,https://www.instagram.com/dentalexpertos,4.9
15,Royal Dental Care,"Centro Empresarial Mondongos, Cl 10 #38 54 502...",320 8201361,http://royaldentalcare.co/,4.8
16,Bioestética Dental,"Cq. 4 #66 b 6, Laureles - Estadio, Medellín, L...",302 7002000,https://sites.google.com/view/bioesteticadental/,4.9
17,ORAL MAS ESPECIALISTAS,"Cl 44 #68 A 43 INT 201, Laureles - Estadio, Me...",312 2563272,https://oralmas.com/,5.0
18,Odontología 30a,"Cl. 30A #7148, Medellín, Belén, Medellín, Anti...",315 4148548,,4.6
19,Clínica Viena / Veneers Medellín,"Cl. 7 Sur #n 42-70 of 420, El Poblado, Medellí...",322 4776418,https://clinicaviena.com/,5.0
20,Ortounion Clínica Odontológica,"Centro Comercial SanDiego, bloque norte, consu...",311 7678677,https://www.ortounion.com/,5.0
21,Consultorio Odontológico Vida Oral,"Cra. 78 #3057, Medellín, Belén, Medellín, Anti...",313 5912089,,5.0
22,Centro Odontológico San Martin,"Cl. 50b #37-82, La Candelaria, Medellín, La Ca...",310 4030712,https://odontologiasanmartin.com/,4.8
23,"URGENCIAS ODONTOLOGICAS, MEDELLÍN","Av. 80 #48b-34, Laureles - Estadio, Medellín, ...",315 4870209,,4.4
24,Smile Natural Studio | Clínica & Spa Odontológico,"Cl. 19a #44-25 Consultorio 1217, El Poblado, M...",300 6370177,https://smilenaturalstudio.com/,5.0
25,Centro Radiológico Oral Centro de Medellin,"Cra. 46 #54 - 14 consultorio 711A, La Candelar...",301 6498722,,5.0
26,DentiOral - Sede Belén,"Cl. 30 #75-64, Medellín, Belén, Medellín, Anti...",(604) 4448911,https://www.dentioral.com/,4.8
27,Odontología The Best Smile Centro Medellín,"Cra 47 / Sucre #56-35, La Candelaria, Medellín...",311 8295100,https://thebestsmileod.com/,4.9
28,Dra Liliana Gutiérrez L.,"050034, Cra 77 #48a 7, Medellín, Antioquia, Co...",300 2357562,http://draliligutierrez.com/,5.0
29,Bocas&Risas - Clínica Odontológica en Medellín,"Cra. 49 # 61 - 42, La Candelaria, Medellín, La...",301 3248706,https://www.bocasyrisas.com/,5.0
30,Odontoss Centro,Cra 46 # 47-66 local 3034 Centro comercial pun...,(604) 4440062,http://www.odontoss.com/,4.7
31,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4
32,Oral Elite Consultorio Odontológico atendido p...,"Cl. 52 #43 - 84, La Candelaria, Medellín, La C...",300 4243602,,5.0
33,Sanadent,"Florida Parque Comercial, Cl. 71 #65 - 150 Loc...",(604) 4486126,https://sanadentodontologos.com.co/,4.9
34,Dentilandia Odontología para Niños / Odontoped...,"Dg. 75B #2 A - 80, Medellín, Belén, Medellín, ...",314 8539100,https://dentilandia.com.co/,4.9
35,Dr. Mauricio Arias - Odontólogo Experto en Med...,"Cra. 76 #32D 31 Oficina 102, Laureles - Estadi...",304 6705124,https://mauricioariasexperience.com/,4.9
36,Oralimagen,"Edificio Consorcio Ejecutivo, 050031, Tv. 74 #...",316 7449425,http://www.oralimagen.com/,5.0
37,MDental Láser,"Cra 43a #7-50 Oficina 408 05000, Medellín, Ant...",320 6896499,http://mdentalaser.com/,5.0
38,Clínica Unilaser,"Calle 7 # 39 - 197 Ed. Torre Intermedica, Cons...",301 2792874,https://clinicaunilaser.com/,4.9
39,Oral + ortodoncia,"Cl 44 #68 a 28, Laureles - Estadio, Medellín, ...",317 6547894,https://oralmas.com/,5.0
40,Odontólogos y Especialistas,"Carrera 80 #32ee-3 a 32ee-69,, Medellín, Antio...",44112100,,5.0
41,Trébol Odontología Especializada Medellín,"Cra. 80A #32-204, Medellín, Belén, Medellín, A...",318 8297858,https://trebolodontologia.com/,4.9
42,Clínica Odontológica Oral Laser Centro,"Edificio Vicente Uribe Rendón, Cra. 46 #52-36 ...",(604) 4440840,https://oralaser.com.co/,4.3
43,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0
44,Consultorio odontológico Smiley,"Cl. 40 #74-14, Laureles - Estadio, Medellín, L...",300 8108091,,5.0
45,Centro Médico Buenos Aires,"Calle 49 33 - 23 Centro, Medellín, Antioquia, ...",(604) 2173938,http://www.centromedicobuenosairesmedellin.com/,3.1
46,"Odontocer, Centro de Estética y Rehabilitación...","Cl. 32F #75c-86 Cons. 602, Edificio 3/33, Mede...",(604) 7738931,http://www.odontocer.com/,5.0
47,CM Odontología,"Centro Comercial Orquídea Plaza, Cra. 49 #52-8...",300 5132274,,5.0
48,Odontologos en Medellin,"Centro Comercial Unicentro, Consultorio 1, Cra...",305 2581651,https://odontologoenmedellin.com/,4.0
49,Innova Odontologos Especialistas,"edificio centro 39, Tv. 39B #73 A 21, Laureles...",321 6465184,http://innovaoe.com/,5.0
50,Focus Dental Center Odontología,"Bh Hotel, Cra. 43A #9 Sur - 6, El Poblado, Med...",350 3454575,,4.9
51,Odontopraxis | Odontología Medellín | Odontológos,"Barrio San Rafael, Cl. 9 Sur #52-06, Guayabal,...",321 2625645,http://www.odontopraxismed.com/,4.9
52,CENTRO DENTAL LA ESPERANZA,"Cra. 56c #55-18, La Candelaria, Medellín, La C...",319 5233338,,5.0
53,Clinica Odontoser,"Centro Comercial Obelisco, Cra. 74 #48-37 37 I...",311 7197264,http://www.odontoser.com.co/,4.9
54,Dental Specialists Medellín,"Torre Médica 2, Centro Comercial El Tesoro #Of...",300 7008281,https://dentalmedellin.com/,5.0
55,Ana Virgen Smile,"Cra. 52 #45 - 92 Local 215, La Candelaria, Med...",311 3669272,,5.0
56,Camila Paredes Odontología,"Centro Profesional Conquistadores, Cl. 34 #63B...",324 5813771,https://www.doctoralia.co/camila-paredes/odont...,5.0
57,Odontología Especializada Medellín,"Torre Medica 2, Cra 25A # 1A Sur, Centro Comer...",300 7008281,,4.8
58,DentiSalud El Poblado - Clínicas Odontológicas,"Av. El Poblado #14s1, El Poblado, Medellín, El...",(604) 3495900,http://www.dentisalud.com.co/,4.5
59,Clínica Odontológica Visión de las Américas,"Carrera 50, Av. Palacé #54-50, Medellín, Antio...",44114848,http://www.uam.edu.co,4.7

In [24]:
import requests
import re
import pandas as pd

df = pd.read_excel("leads_odontologos_medellin.xlsx")

def extraer_email(url):
    if not url or pd.isna(url):
        return ""
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=8)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', response.text)
        emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example'])]
        return emails[0] if emails else ""
    except:
        return ""

print("Extrayendo emails...")
df["Email"] = ""

for i, row in df.iterrows():
    email = extraer_email(row.get("Web"))
    df.at[i, "Email"] = email
    estado = "OK" if email else "sin email"
    print(f"{row['Nombre']} --> {email if email else estado}")

df.to_excel("leads_odontologos_medellin.xlsx", index=False)
print(f"\nEmails encontrados: {df['Email'].ne('').sum()} de {len(df)}")
df

Extrayendo emails...
Centro odontológico KMO Smile Especialistas --> sin email
Premium Dental Medellín --> premiumdentalmedellin@gmail.com
Clínica Dental Home --> info@clinicadentalhome.net
ORAL CONCEPT INVISALIGN --> sin email
Odontología la 78 Urgencia las 24 horas --> sin email
Odontoespecialistas --> gerencia@odontoespecialistas.com
Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín --> bg-vertical-tabs@2x.png
Dental Center --> Pacientesdc@gmail.com
Consultorio odontologico la 73 --> odontologosla73@gmail.com
Infinity Smile --> sin email
Oral Studio --> correo@correo.com
Dentioral - Sede Poblado --> info@dentioral.com
Sanadent Odontólogos - La Mejor Clínica Dental en Medellín --> sin email
CR Dental Studio --> sin email
Dental Expertos --> sin email
Royal Dental Care --> Mesa-de-trabajo-12@2x.png
Bioestética Dental --> bioesteticadental69@gmail.com
ORAL MAS ESPECIALISTAS --> sin email
Odontología 30a --> sin email
Clínica Viena / Veneers Medellín --> gerencia@clinicaviena.com.co
Ortounion Clínica Odontológica --> info@ortounion.com
Consultorio Odontológico Vida Oral --> sin email
Centro Odontológico San Martin --> sin email
URGENCIAS ODONTOLOGICAS, MEDELLÍN --> sin email
Smile Natural Studio | Clínica & Spa Odontológico --> usuario@mail.com
Centro Radiológico Oral Centro de Medellin --> sin email
DentiOral - Sede Belén --> info@dentioral.com
Odontología The Best Smile Centro Medellín --> thebestsmileod@gmail.com
Dra Liliana Gutiérrez L. --> sin email
Bocas&Risas - Clínica Odontológica en Medellín --> sin email
Odontoss Centro --> gerencia@odontoss.com
Oral Center Poblado --> sin email
Oral Elite Consultorio Odontológico atendido por el Dr Alejandro Ramírez --> sin email
Sanadent --> sin email
Dentilandia Odontología para Niños / Odontopediatria Medellin --> sin email
Dr. Mauricio Arias - Odontólogo Experto en Medellín English Dentist --> sin email
Oralimagen --> siev@siev.com.co
MDental Láser --> mdentalaser@gmail.com
Clínica Unilaser --> sin email
Oral + ortodoncia --> sin email
Odontólogos y Especialistas --> sin email
Trébol Odontología Especializada Medellín --> sin email
Clínica Odontológica Oral Laser Centro --> Mesa-de-trabajo-175@150x-100-10.jpg
Odontología el Poblado - Oral 10 - Diseños de Sonrisa en Medellín --> oral10vegas@gmail.com
Consultorio odontológico Smiley --> sin email
Centro Médico Buenos Aires --> cmbuenosaires2@gmail.com
Odontocer, Centro de Estética y Rehabilitación Oral --> comunicaciones@odontocer.com
CM Odontología --> sin email
Odontologos en Medellin --> sin email
Innova Odontologos Especialistas --> info@innovaoe.com
Focus Dental Center Odontología --> sin email
Odontopraxis | Odontología Medellín | Odontológos --> hola@odontopraxismed.com
CENTRO DENTAL LA ESPERANZA --> sin email
Clinica Odontoser --> info@odontoser.com.co
Dental Specialists Medellín --> contact@dentalmedellin.com
Ana Virgen Smile --> sin email
Camila Paredes Odontología --> soporte@doctoralia.com
Odontología Especializada Medellín --> sin email
DentiSalud El Poblado - Clínicas Odontológicas --> info@dentisalud.com.co
Clínica Odontológica Visión de las Américas --> sin email

Emails encontrados: 28 de 60

,Nombre,Dirección,Teléfono,Web,Rating,Email
0,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,
1,Premium Dental Medellín,"Local 2101. CC Premium Plaza, El Poblado, Mede...",320 4010740,http://premiumdentalmedellin.com/,4.9,premiumdentalmedellin@gmail.com
2,Clínica Dental Home,"Cl. 34 #34A-76 Consultorio 401, Laureles - Est...",310 4194654,https://clinicadentalhome.com/?utm_source=goog...,4.9,info@clinicadentalhome.net
3,ORAL CONCEPT INVISALIGN,"Cra. 70 #32 b 51 local 1, Medellín, Belén, Med...",313 7662008,https://oralconcept.co/home/oral-concept,5.0,
4,Odontología la 78 Urgencia las 24 horas,"Cl. 45A #77 a 10, Los Pinos, Medellín, Laurele...",312 2478447,https://consultorioodontologicola78.com/,4.3,
5,Odontoespecialistas,"Calle 34 ##43-66 Local 1008 1009, Medellín, An...",313 7591236,http://www.odontoespecialistas.com/,5.0,gerencia@odontoespecialistas.com
6,Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín,"Cra. 43A #18sur-135 piso 9, oficina 910, El Po...",305 4566979,http://www.dranazuluaga.com/,4.9,bg-vertical-tabs@2x.png
7,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com
8,Consultorio odontologico la 73,"AKT Colombia, Cl 44 #73 - 12 segundo piso, Lau...",318 7501226,http://www.odontologosla73.com/,4.9,odontologosla73@gmail.com
9,Infinity Smile,"Cra. 78A #34-41, Laureles - Estadio, Medellín,...",323 4650026,https://infinitysmile.com.co/,4.9,
10,Oral Studio,"Cl. 19a # 44 - 25 Consultorio 2001, El Poblado...",312 7093687,https://www.oralstudio.com.co/,5.0,correo@correo.com
11,Dentioral - Sede Poblado,"Cra. 43A #34-95 Local 200, Centro comercial Al...",(604) 4448911,https://dentioral.com/,5.0,info@dentioral.com
12,Sanadent Odontólogos - La Mejor Clínica Dental...,"Av. 33 #· 81 - 17, Laureles - Estadio, Medellí...",(604) 4486126,http://www.sanadentodontologos.com.co/,4.9,
13,CR Dental Studio,"sector Las Lomas Edificio C13, Cra. 32 #13-49 ...",302 3291500,https://www.instagram.com/crdentalstudio/,5.0,
14,Dental Expertos,"Cra. 52 # 7-115, Guayabal, Medellín, Guayabal,...",300 8938020,https://www.instagram.com/dentalexpertos,4.9,
15,Royal Dental Care,"Centro Empresarial Mondongos, Cl 10 #38 54 502...",320 8201361,http://royaldentalcare.co/,4.8,Mesa-de-trabajo-12@2x.png
16,Bioestética Dental,"Cq. 4 #66 b 6, Laureles - Estadio, Medellín, L...",302 7002000,https://sites.google.com/view/bioesteticadental/,4.9,bioesteticadental69@gmail.com
17,ORAL MAS ESPECIALISTAS,"Cl 44 #68 A 43 INT 201, Laureles - Estadio, Me...",312 2563272,https://oralmas.com/,5.0,
18,Odontología 30a,"Cl. 30A #7148, Medellín, Belén, Medellín, Anti...",315 4148548,NaN,4.6,
19,Clínica Viena / Veneers Medellín,"Cl. 7 Sur #n 42-70 of 420, El Poblado, Medellí...",322 4776418,https://clinicaviena.com/,5.0,gerencia@clinicaviena.com.co
20,Ortounion Clínica Odontológica,"Centro Comercial SanDiego, bloque norte, consu...",311 7678677,https://www.ortounion.com/,5.0,info@ortounion.com
21,Consultorio Odontológico Vida Oral,"Cra. 78 #3057, Medellín, Belén, Medellín, Anti...",313 5912089,NaN,5.0,
22,Centro Odontológico San Martin,"Cl. 50b #37-82, La Candelaria, Medellín, La Ca...",310 4030712,https://odontologiasanmartin.com/,4.8,
23,"URGENCIAS ODONTOLOGICAS, MEDELLÍN","Av. 80 #48b-34, Laureles - Estadio, Medellín, ...",315 4870209,NaN,4.4,
24,Smile Natural Studio | Clínica & Spa Odontológico,"Cl. 19a #44-25 Consultorio 1217, El Poblado, M...",300 6370177,https://smilenaturalstudio.com/,5.0,usuario@mail.com
25,Centro Radiológico Oral Centro de Medellin,"Cra. 46 #54 - 14 consultorio 711A, La Candelar...",301 6498722,NaN,5.0,
26,DentiOral - Sede Belén,"Cl. 30 #75-64, Medellín, Belén, Medellín, Anti...",(604) 4448911,https://www.dentioral.com/,4.8,info@dentioral.com
27,Odontología The Best Smile Centro Medellín,"Cra 47 / Sucre #56-35, La Candelaria, Medellín...",311 8295100,https://thebestsmileod.com/,4.9,thebestsmileod@gmail.com
28,Dra Liliana Gutiérrez L.,"050034, Cra 77 #48a 7, Medellín, Antioquia, Co...",300 2357562,http://draliligutierrez.com/,5.0,
29,Bocas&Risas - Clínica Odontológica en Medellín,"Cra. 49 # 61 - 42, La Candelaria, Medellín, La...",301 3248706,https://www.bocasyrisas.com/,5.0,
30,Odontoss Centro,Cra 46 # 47-66 local 3034 Centro comercial pun...,(604) 4440062,http://www.odontoss.com/,4.7,gerencia@odontoss.com
31,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,
32,Oral Elite Consultorio Odontológico atendido p...,"Cl. 52 #43 - 84, La Candelaria, Medellín, La C...",300 4243602,NaN,5.0,
33,Sanadent,"Florida Parque Comercial, Cl. 71 #65 - 150 Loc...",(604) 4486126,https://sanadentodontologos.com.co/,4.9,
34,Dentilandia Odontología para Niños / Odontoped...,"Dg. 75B #2 A - 80, Medellín, Belén, Medellín, ...",314 8539100,https://dentilandia.com.co/,4.9,
35,Dr. Mauricio Arias - Odontólogo Experto en Med...,"Cra. 76 #32D 31 Oficina 102, Laureles - Estadi...",304 6705124,https://mauricioariasexperience.com/,4.9,
36,Oralimagen,"Edificio Consorcio Ejecutivo, 050031, Tv. 74 #...",316 7449425,http://www.oralimagen.com/,5.0,siev@siev.com.co
37,MDental Láser,"Cra 43a #7-50 Oficina 408 05000, Medellín, Ant...",320 6896499,http://mdentalaser.com/,5.0,mdentalaser@gmail.com
38,Clínica Unilaser,"Calle 7 # 39 - 197 Ed. Torre Intermedica, Cons...",301 2792874,https://clinicaunilaser.com/,4.9,
39,Oral + ortodoncia,"Cl 44 #68 a 28, Laureles - Estadio, Medellín, ...",317 6547894,https://oralmas.com/,5.0,
40,Odontólogos y Especialistas,"Carrera 80 #32ee-3 a 32ee-69,, Medellín, Antio...",44112100,NaN,5.0,
41,Trébol Odontología Especializada Medellín,"Cra. 80A #32-204, Medellín, Belén, Medellín, A...",318 8297858,https://trebolodontologia.com/,4.9,
42,Clínica Odontológica Oral Laser Centro,"Edificio Vicente Uribe Rendón, Cra. 46 #52-36 ...",(604) 4440840,https://oralaser.com.co/,4.3,Mesa-de-trabajo-175@150x-100-10.jpg
43,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com
44,Consultorio odontológico Smiley,"Cl. 40 #74-14, Laureles - Estadio, Medellín, L...",300 8108091,NaN,5.0,
45,Centro Médico Buenos Aires,"Calle 49 33 - 23 Centro, Medellín, Antioquia, ...",(604) 2173938,http://www.centromedicobuenosairesmedellin.com/,3.1,cmbuenosaires2@gmail.com
46,"Odontocer, Centro de Estética y Rehabilitación...","Cl. 32F #75c-86 Cons. 602, Edificio 3/33, Mede...",(604) 7738931,http://www.odontocer.com/,5.0,comunicaciones@odontocer.com
47,CM Odontología,"Centro Comercial Orquídea Plaza, Cra. 49 #52-8...",300 5132274,NaN,5.0,
48,Odontologos en Medellin,"Centro Comercial Unicentro, Consultorio 1, Cra...",305 2581651,https://odontologoenmedellin.com/,4.0,
49,Innova Odontologos Especialistas,"edificio centro 39, Tv. 39B #73 A 21, Laureles...",321 6465184,http://innovaoe.com/,5.0,info@innovaoe.com
50,Focus Dental Center Odontología,"Bh Hotel, Cra. 43A #9 Sur - 6, El Poblado, Med...",350 3454575,NaN,4.9,
51,Odontopraxis | Odontología Medellín | Odontológos,"Barrio San Rafael, Cl. 9 Sur #52-06, Guayabal,...",321 2625645,http://www.odontopraxismed.com/,4.9,hola@odontopraxismed.com
52,CENTRO DENTAL LA ESPERANZA,"Cra. 56c #55-18, La Candelaria, Medellín, La C...",319 5233338,NaN,5.0,
53,Clinica Odontoser,"Centro Comercial Obelisco, Cra. 74 #48-37 37 I...",311 7197264,http://www.odontoser.com.co/,4.9,info@odontoser.com.co
54,Dental Specialists Medellín,"Torre Médica 2, Centro Comercial El Tesoro #Of...",300 7008281,https://dentalmedellin.com/,5.0,contact@dentalmedellin.com
55,Ana Virgen Smile,"Cra. 52 #45 - 92 Local 215, La Candelaria, Med...",311 3669272,NaN,5.0,
56,Camila Paredes Odontología,"Centro Profesional Conquistadores, Cl. 34 #63B...",324 5813771,https://www.doctoralia.co/camila-paredes/odont...,5.0,soporte@doctoralia.com
57,Odontología Especializada Medellín,"Torre Medica 2, Cra 25A # 1A Sur, Centro Comer...",300 7008281,NaN,4.8,
58,DentiSalud El Poblado - Clínicas Odontológicas,"Av. El Poblado #14s1, El Poblado, Medellín, El...",(604) 3495900,http://www.dentisalud.com.co/,4.5,info@dentisalud.com.co
59,Clínica Odontológica Visión de las Américas,"Carrera 50, Av. Palacé #54-50, Medellín, Antio...",44114848,http://www.uam.edu.co,4.7,

In [25]:
import requests
import pandas as pd
import time
import re

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"
url_details = "https://maps.googleapis.com/maps/api/place/details/json"

# Todas las zonas de busqueda
zonas = [
    "centros odontologicos El Poblado Medellin",
    "centros odontologicos Laureles Medellin",
    "centros odontologicos Envigado",
    "centros odontologicos Bello",
    "centros odontologicos Itagui",
    "centros odontologicos Centro Medellin",
    "centros odontologicos Sabaneta",
    "centros odontologicos Belen Medellin",
    "centros odontologicos Robledo Medellin",
    "centros odontologicos Castilla Medellin"
]

todos_leads = []
ids_vistos = set()

def extraer_email(url):
    if not url or pd.isna(url):
        return ""
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=8)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', response.text)
        emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example'])]
        return emails[0] if emails else ""
    except:
        return ""

for zona in zonas:
    print(f"\nBuscando: {zona}")
    params = {"query": zona, "key": API_KEY, "language": "es"}
    
    while True:
        response = requests.get(url_search, params=params).json()
        
        for place in response.get("results", []):
            place_id = place.get("place_id", "")
            
            if place_id in ids_vistos:
                continue
            ids_vistos.add(place_id)
            
            details = requests.get(url_details, params={
                "place_id": place_id,
                "fields": "formatted_phone_number,website",
                "key": API_KEY
            }).json()
            
            web = details.get("result", {}).get("website", "")
            email = extraer_email(web)
            
            todos_leads.append({
                "Nombre": place.get("name", ""),
                "Direccion": place.get("formatted_address", ""),
                "Telefono": details.get("result", {}).get("formatted_phone_number", ""),
                "Web": web,
                "Rating": place.get("rating", ""),
                "Email": email,
                "Zona": zona
            })
            print(f"OK: {place.get('name')}")
        
        next_page_token = response.get("next_page_token")
        if next_page_token:
            time.sleep(3)
            params = {"pagetoken": next_page_token, "key": API_KEY}
        else:
            break

df = pd.DataFrame(todos_leads)
df.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"\nTotal leads unicos guardados: {len(todos_leads)}")
df

Buscando: centros odontologicos El Poblado Medellin
OK: Oral Center Poblado
OK: Dental Center
OK: Centro odontológico KMO Smile Especialistas
OK: Poblado Dental
OK: Odontología el Poblado - Oral 10 - Diseños de Sonrisa en Medellín
OK: ORAL DESIGN POBLADO
OK: Oral Studio
OK: Dra. Maru Odontología y Estética Facial
OK: Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín
OK: Smile From Medellin - Dental Clinic
OK: DentiSalud El Poblado - Clínicas Odontológicas
OK: CR Dental Studio
OK: Royal Dental Care
OK: W SMILE premium dental practice
OK: Premium Dental Medellín
OK: Smile Natural Studio | Clínica & Spa Odontológico
OK: Clínica Viena / Veneers Medellín
OK: MY DENTAL
OK: Dentioral - Sede Poblado
OK: Present Dental Studio
OK: Dra. Carolina Bermúdez
OK: Centro Vital, Odontología Integral
OK: Clínica Unilaser
OK: Valo Dental Studio
OK: MDental Láser
OK: Dora Álvarez
OK: Focus Dental Center Odontología
OK: Dental Specialists Medellín
OK: Jenny Villada Clínicas Odontológicas
OK: Smile Dental Center Medellín | Carillas Dentales y Diseño de Sonrisa
OK: Clinica odontologica Dra Vanessa Corrales
OK: Ortodoncia Dental Medellin
OK: Lina Fernández Odontología - Diseño de sonrisa y Blanqueamiento dental en Medellín
OK: CLINICA DENTAL POBLADO
OK: Clínica Dental Home
OK: Odontología OPAL - DISEÑO DE SONRISA - CORONAS DENTALES
OK: Syma Clínica Odontológica
OK: Beaming Dental Clinic | Clínica dental en Colombia
OK: ODONTOLOGÍA Y ORTODONCIA MEDELLIN - ORALCOMPANY
OK: Orthoarte Poblado
OK: Dental Planet Odontopediatria
OK: Odontólogo Ces
OK: Colmédica Medellin El Poblado - Centro Médico y Odontológico - Oficina
OK: Odontología Especializada Medellín
OK: Turismo Dental Colombia - Dr. Camilo Aguirre
OK: Clínica Odontológica PROMTA - Sede Poblado
OK: Dental Expertos
OK: ORAL CONCEPT INVISALIGN
OK: Ortodoncia Funcional CG
OK: Clínica Dental Home
OK: Hi Dental IPS

Buscando: centros odontologicos Laureles Medellin
OK: Odontoss Laureles
OK: LaborDental Laureles
OK: Alta Estetica Dental Laureles
OK: Consultorio odontológico Smiley
OK: ORAL MAS ESPECIALISTAS
OK: Infinity Smile
OK: Dra Juliana Fernández J
OK: Dra Liliana Gutiérrez L.
OK: Consultorio odontologico la 73
OK: Sanadent Odontólogos - La Mejor Clínica Dental en Medellín
OK: Luminux Odontología Integral y Estética, Laureles
OK: Odontología la 78 Urgencia las 24 horas
OK: Neodental Centro Odontológico Laureles
OK: Dr. Mauricio Arias - Odontólogo Experto en Medellín English Dentist
OK: Oralimagen
OK: Odontologos en Medellin
OK: Centro Odontológico Orthoplan Laureles
OK: Paula Ramírez Consultorio Odontológico
OK: Oral + ortodoncia
OK: Camila Paredes Odontología
OK: Casa De Sonrisas
OK: Alternativas Odontológicas
OK: Centro Aliado Moons Laureles
OK: CLÍNICA DENTAL ALEGRA SEDE LAURELES
OK: Centro Odontológico White Dental
OK: Dentix Laureles
OK: WS Medellin - ODONTOLOGIA ESTETICA ESPECIALIZADA
OK: OdontoestéticaDH
OK: Teran Florez Odontología Especializada
OK: Mastic Odontología
OK: Naturaldent
OK: Innova Odontologos Especialistas
OK: URGENCIAS ODONTOLOGICAS, MEDELLÍN
OK: Ortoclin Sede Laureles
OK: Oral Center Distrito 65
OK: Dental Exclusive
OK: DentiSalud Floresta - Clínica odontológica
OK: Dento Grupo Odontológico
OK: Natural odontología
OK: Clínica Colombiana de Implantes Dentales
OK: Dr. JAIME VARGAS Consultorio Odontológico 211
OK: Nova Dental Studio
OK: Trébol Odontología Especializada Medellín
OK: Dra Tamayo Centro Odontológico
OK: Ortoclin Sede Santa Lucia
OK: Clínica Odontológica Oral Laser Estadio
OK: Ópalo Odontología Estética
OK: Odontólogos y Especialistas
OK: Happy Dental
OK: Ortoclin Sede Floresta
OK: Dentales Antioquia S.A.S
OK: CERO 70 SAS - Sede Laureles
OK: Centro Integral de Salud Oral Los Laureles
OK: Clínica Odontológica Punto Oral S.A
OK: IPS Odontología San Juan
OK: ODONTOLOGIA EL NOGAL
OK: Space. Centro radiológico oral cero 70, la 33
OK: Sonría
OK: ORAL-TEC

Buscando: centros odontologicos Envigado
OK: True Smile Clinica odontologica en Envigado
OK: Marr Dental - Clínica odontológica en Medellín
OK: Unidad Médica Odontológica - Odontología Especializada
OK: Prevenga Odontología Particular - Envigado
OK: Clinica Odontológica Oral Laser Envigado
OK: OdontoSur Clínica
OK: NaturalDent Envigado
OK: Ortoclin Sede Envigado
OK: LK Dental Odontología General y Especializada en Envigado | Diseño de Sonrisa
OK: Clínica Odontológica Dra. Paula Muñoz.
OK: Odox clínica odontológica envigado
OK: Odontología Dental Bliss - Sede Envigado
OK: Centro Odontológico Clean Smile
OK: Odontologo en Envigado Dra. Edith Ofelia Pardo
OK: 32 rocks, clinica dental envigado
OK: Consultorio Odontologico El Dorado
OK: Odontología Especializada El Escobero Envigado Dra. Yamile Atehortua
OK: Consultorio Odontológico Carolina Herrera
OK: Olivo Odontologia
OK: CENTRO ODONTOLOGICO DE ANTIOQUIA
OK: CEO - Centro Estético Odontológico
OK: Dra. Jessica Londoño
OK: Juliana Rojas Odontología
OK: lets smile envigado
OK: SMILE Clínica Odontológica sede Envigado
OK: Dentalix Clinic
OK: Consultorio Odontológico Gilma Garcia
OK: Innova Dental Odontología
OK: Odontología Sara Restrepo Vélez
OK: Smile Odontólogos
OK: Odontolam, Odontológos Especialistas
OK: Envigado Dental Design Dr. Hugo Sánchez
OK: Consultorio Odontológico Odontología Familiar
OK: OdontoSonrisasenvigado
OK: Envigado Oral
OK: COA-Centro Oncológico de Antioquia
OK: Odontoexpertos envigado
OK: OdontoZane
OK: Dentus Odontologia Integral
OK: ALMA DENTAL
OK: AllDent Odontología Especializada
OK: Odontologo Daniel Restrepo Salazar
OK: Urgencias Odontológicas 24 horas las Vegas
OK: CERO 70 SAS - Sede Envigado
OK: Clinica de Implantes Dentales del Sur
OK: PARA ODONTÓLOGOS S.A.S.
OK: Dra. Angela María Tamayo Posada
OK: magna clínica dental
OK: Bucco "Odontología De Alto Nivel"
OK: ORTODIAGNOSTICO
OK: Dra.Patricia Alvarez Gomez
OK: Angela Guevara Odontología Integrativa
OK: CENTRO ODONTOLOGICO ASDENTAL
OK: Consultorio Odontológico (Anteriormente Esmar Odontología Especializada)
OK: CEROMA
OK: Consultorio Odontológico OC
OK: Stetika Odontologia
OK: Vivartec - Odontología

Buscando: centros odontologicos Bello
OK: Dentotal
OK: Odontología Especializada | Dra. Libia Espinosa
OK: Centro Especializado Odontológico
OK: Oral Center Bello
OK: Smile Me
OK: Centro Odontológico Integral Maxsy
OK: Punto Odontológico
OK: Consultorio Odontológico Avenida
OK: Consultorio y laboratorio dental Jesús Arroyave (Dra. Lisbeth Velasquez)
OK: Odonto Innova
OK: Dra. Astrix Vivas | Odontología general y estética
OK: Dra. Libia Espinosa S
OK: Dental line
OK: CONSULTORIO ODONTOLOGICO Y LABORATORIO DENTAL SAN JOSE
OK: Centro Odontológico la Cabaña
OK: Odontología Jorge García S.A.S
OK: Hidental IPS Sede Bello
OK: ODONTOINSUMOS
OK: Dent Sonrisas Centro Odontologico
OK: Oraldent
OK: Consultorio Odontologíco Somos Dental
OK: Odontoclave Bello Fabricato
OK: Biodent Centro odontológico
OK: Hola Odontología
OK: Oralis Odontologia + Estetica
OK: Kdent
OK: Comfama Bello Sede Centro
OK: Medibello
OK: Consultorio Odontológico Angela Maria Rodriguez
OK: Consultorio Odontológico Maxident
OK: Super Sonrisas (sede cabañas)
OK: Tu Salud Oral Clínica Dental
OK: Maxi Sonrisas
OK: Centro Odontológico Camilo Gallego Zea
OK: Cuidarte Clínicas Odontológicas
OK: Arte y Boca Niquia
OK: Dental Solution
OK: Centro Ejecutivo Cristal
OK: Oficentro
OK: MYM odontología
OK: Oral Medic
OK: Ortolife
OK: ODONTOCLAVE FABRICATO
OK: ESE Bellosalud Rosalpi
OK: Consultorio Y Laboratorio Odontológico San Ignacio
OK: Centro comercial Parque Fabricato

Buscando: centros odontologicos Itagui
OK: Super Smile
OK: Prevenga Odontología Particular - Itagüí
OK: estilo Oral
OK: Clínica Odontológica Oral Laser Itagüi
OK: Espacio Dental
OK: Oral Sonrie
OK: Odontoss Itagui
OK: Consultorio Odontológico El Carmelo
OK: Dr. Andrés Fuertes odontología ética y responsable.
OK: DentiSalud Itagui
OK: URGENCIAS ODONTOLÓGICAS ITAGÜÍ
OK: Dentiplan Itagüí
OK: Odontologos Santamaria
OK: Urgencias Odontologicas del Sur
OK: Consultorio odontológico gdental
OK: Centro De Radiologia Oral Jg Itagüi
OK: MP ODONTOLOGÍA
OK: Clínica Odontologica Mundo Sonrisas
OK: Élite Smile
OK: Odontología en itagui Dra. Alejandra Ruiz Uribe
OK: Consultorio Odontólogico Dra Lady Castaño
OK: Consultorio odontológico Dr Anderson Echeverry
OK: DENTSONRISAS
OK: Natural Dent Itagui
OK: Consultorio Odontológico Biodental HH
OK: Dentali odontología - Sede Itagüí
OK: Natural Concept Odontólogos
OK: CS&CS Salud Oral y Piel
OK: Odontología Segura
OK: Dr DNY Odontología Sabaneta
OK: Dental Clinique
OK: Consultorio Odontologico Dr. Freiman Alvarez
OK: Innovarte Dental
OK: Diagnostico Digital
OK: Odontología - Dientes Sanos Itagüí
OK: DENTAL CLINIC GRUPO ODONTOLOGICO
OK: Centro Comercial La Gran manzana
OK: ODONTOLOGIA INTEGRAL
OK: Odontics Sabaneta
OK: Odontologia Integral Itagui
OK: Consultorio Odontólogico El Buen Samaritano
OK: 360 Dental Group IPS | Clínica Odontológica Mayorca
OK: Clínica Total Harmony - Dr. Edison Giraldo
OK: Dra. Lisbed Giraldo Olarte, Odontólogo
OK: La Feria Dental
OK: Maxdentall
OK: Santa Teresita Centro Odontológico
OK: Consultorio Odontológico Clara Sonrisa
OK: Centro Odontológico Estética Dental
OK: Centro Comercial y empresarial Itagüí Plaza
OK: Odontologa Eliana Gomez
OK: Clinica Odontológica Orthodox Mayorca

Buscando: centros odontologicos Centro Medellin
OK: Odontoespecialistas
OK: Odontología The Best Smile Centro Medellín
OK: Centro Odontológico San Martin
OK: Centro Radiológico Oral Centro de Medellin
OK: Clínica Odontologica Oral Centro
OK: Ortounion Clínica Odontológica
OK: Clínica Odontológica Oral Laser Centro
OK: Odontoss Centro
OK: Bocas&Risas - Clínica Odontológica en Medellín
OK: Oral Elite Consultorio Odontológico atendido por el Dr Alejandro Ramírez
OK: CERO70 SAS - Sede Centro
OK: Consultorio Odontológico Vida Oral
OK: CENTRO DENTAL LA ESPERANZA
OK: CM Odontología
OK: Centro Médico Buenos Aires
OK: centroral
OK: Odontología Ana María Martínez
OK: Ana Virgen Smile
OK: Sanadent
OK: Másdental Sede San Diego
OK: DIENTES SANOS MEDELLIN
OK: DentiOral - Sede Belén
OK: Centro Odontológico Congregación Mariana
OK: centro odontologico la 65
OK: Clínica Odontológica de Antioquia - CLODAN sas.
OK: Odonto Rio - Estudio Dental
OK: Centro Odontológico La Oriental
OK: Sede Centro - PROMTA Clínica Odontológica
OK: Consultorio odontológico Angela Zapata
OK: Centro Comercial El Punto de La Oriental
OK: StarNova Consultorio Odontologico By Juan Pablo Lopera
OK: ORAL DESIGN CENTRO
OK: Dens Clinicas Dentales

Buscando: centros odontologicos Sabaneta
OK: Dental clinic soluciones odontologicas
OK: CREADENTISS, odontología integral
OK: CIO Clínica Dental
OK: dr perfect smile sabaneta
OK: Tooth Dentistry
OK: Odontoss Sabaneta
OK: OralZen
OK: orthowhite sabaneta
OK: Deluxe Smile
OK: All Smiles Odontología
OK: Consultorio Odontologico Dr. Juan Fernando Acevedo Vergara
OK: odontomaster
OK: Javier Vanegas Odontólogos Especialistas
OK: Santé - Odontología Integral
OK: Radiológica Diagnóstico oral
OK: Eliana Yepes - Consultorio Odontológico
OK: Luminux Odontología, Sabaneta
OK: Fenixia Dental Art Odontología
OK: Odontoclave Mayorca
OK: Dental Miracle
OK: SMILE Clínica Odontológica sede Sabaneta
OK: Mundo oral
OK: Odontologia Armonize
OK: CERO 70 SAS - Sede Sabaneta
OK: Centro Dental Dr Gabriel Hurtado

Buscando: centros odontologicos Belen Medellin
OK: Odontología 30a
OK: Dental Master - Dr. Rubén Arbeláez
OK: Odontocer, Centro de Estética y Rehabilitación Oral
OK: Neodental Centro Odontológico
OK: Dr Andres Alvarez Implantologo oral y Rehabiltacion
OK: San José Centro Odontológico
OK: Odontorisas
OK: Orthodontics Medellín
OK: Clinica Dental Sonría BELÉN
OK: Clínica Odontológica Dientes Sanos Belén
OK: SONRIESTHETIC ODONTOLOGÍA
OK: ProSmile Medellín - Expertos en Salud Bucal y Estética Dental
OK: Odontologia Integral OdontoVitha, Profesionales independientes
OK: Centro Odontologico Bulerias
OK: Esencia Dental
OK: ORAL DESIGN - DISEÑO DE SONRISA - VENEERS
OK: Clínica Dental - Belén Dental
OK: Dental smile laboratorio
OK: Clinica Menta
OK: Dental House
OK: Dental Team - SEDE BELÉN (PLAZOLETA NUEVA VILLA DEL ABURRÁ)
OK: Ortho Estetika

Buscando: centros odontologicos Robledo Medellin
OK: Consultorio y laboratorio odontológico Robledo
OK: Centro Odontológico Especializado CARDENT
OK: Consultorio Robledo Odontología Integral
OK: Consultorio odontológico Oral Life Odontología Integral
OK: Consultorio Odontologico Robledo
OK: Centro odontologico vital Dent
OK: Mirando Sonrisas - Urgencias Odontologicas
OK: Centro Odontologico Robledo
OK: Centro Médico y Odontológico La 75
OK: MEDICINA-ODONTOLOGÍA LABORATORIO CLÍNICO

Buscando: centros odontologicos Castilla Medellin
OK: Ortoclin Sede Castilla
OK: Odontologia Integral Castilla
OK: SALUD ORAL CENTER I.P.S S.A.S
OK: Dentali odontología - Sede Castilla
OK: Armony Dental
OK: JKDENTAL
OK: ORAL PLUS Odontología Integral
OK: Consultorio Odontologico Daniela Ruiz Sanchez
OK: Odontovital Tricentenario
OK: Consultorio Odontológico - Miguel Uribe
OK: consultorio odontologíco
OK: Urgencia Odontologicas Castilla
OK: Abba Dent
OK: Laboratorio dental
OK: MJ Odontología Integral
OK: Odontología Especializada
OK: Odontología Aranjuez
OK: RxNortDental
OK: Odontología OVA

Total leads unicos guardados: 375

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,,centros odontologicos El Poblado Medellin
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,,4.9,,centros odontologicos El Poblado Medellin
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin
...,...,...,...,...,...,...,...
370,MJ Odontología Integral,"Cl. 91A # 71 - 30 int 301, Francisco Zea, Mede...",305 3818475,,3,,centros odontologicos Castilla Medellin
371,Odontología Especializada,"Cl. 57 #49-44, La Candelaria, Medellín, La Can...",333 2922519,,5,,centros odontologicos Castilla Medellin
372,Odontología Aranjuez,"Cra. 49A #92-90, Aranjuez, Medellín, Aranjuez,...",310 8388449,https://wa.me/573108388449,4.9,,centros odontologicos Castilla Medellin
373,RxNortDental,"CC Terminal del Norte, Local 156, Oleoducto, M...",,,3.4,,centros odontologicos Castilla Medellin
374,Odontología OVA,"Castilla, Medellín, Castilla, Medellín, Antioq...",,,,,centros odontologicos Castilla Medellin

In [26]:
import requests
import pandas as pd
import re
from urllib.parse import urljoin, urlparse

df = pd.read_excel("leads_odontologos_medellin_completo.xlsx")

def extraer_email_profundo(url):
    if not url or pd.isna(url):
        return ""
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        
        # Primero buscar en la pagina principal
        response = requests.get(url, headers=headers, timeout=8)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', response.text)
        emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example', 'jquery'])]
        if emails:
            return emails[0]
        
        # Si no hay email, buscar en paginas de contacto
        paginas_contacto = [
            urljoin(url, "/contacto"),
            urljoin(url, "/contact"),
            urljoin(url, "/nosotros"),
            urljoin(url, "/about"),
            urljoin(url, "/contactenos"),
        ]
        
        for pagina in paginas_contacto:
            try:
                r = requests.get(pagina, headers=headers, timeout=6)
                if r.status_code == 200:
                    emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', r.text)
                    emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example', 'jquery'])]
                    if emails:
                        return emails[0]
            except:
                continue
        return ""
    except:
        return ""

print("Mejorando extraccion de emails...")

for i, row in df.iterrows():
    if row.get("Email") and not pd.isna(row.get("Email")):
        print(f"YA TIENE: {row['Nombre']} --> {row['Email']}")
        continue
    
    email = extraer_email_profundo(row.get("Web"))
    df.at[i, "Email"] = email
    estado = email if email else "sin email"
    print(f"{row['Nombre']} --> {estado}")

df.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"\nTotal emails: {df['Email'].ne('').sum()} de {len(df)}")
df

Mejorando extraccion de emails...
Oral Center Poblado --> sin email
YA TIENE: Dental Center --> Pacientesdc@gmail.com
Centro odontológico KMO Smile Especialistas --> sin email
YA TIENE: Poblado Dental --> pobladodental@gmail.com
YA TIENE: Odontología el Poblado - Oral 10 - Diseños de Sonrisa en Medellín --> oral10vegas@gmail.com
ORAL DESIGN POBLADO --> sin email
YA TIENE: Oral Studio --> correo@correo.com
Dra. Maru Odontología y Estética Facial --> sin email
YA TIENE: Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín --> bg-vertical-tabs@2x.png
Smile From Medellin - Dental Clinic --> sin email
YA TIENE: DentiSalud El Poblado - Clínicas Odontológicas --> info@dentisalud.com.co
CR Dental Studio --> sin email
YA TIENE: Royal Dental Care --> Mesa-de-trabajo-12@2x.png
W SMILE premium dental practice --> sin email
YA TIENE: Premium Dental Medellín --> premiumdentalmedellin@gmail.com
YA TIENE: Smile Natural Studio | Clínica & Spa Odontológico --> usuario@mail.com
YA TIENE: Clínica Viena / Veneers Medellín --> gerencia@clinicaviena.com.co
MY DENTAL --> sin email
YA TIENE: Dentioral - Sede Poblado --> info@dentioral.com
YA TIENE: Present Dental Studio --> bg-2@2x.jpg
YA TIENE: Dra. Carolina Bermúdez --> dracarobea@gmail.com
Centro Vital, Odontología Integral --> sin email
Clínica Unilaser --> carlos@delaossa.co
YA TIENE: Valo Dental Studio --> info@valodentalstudio.com
YA TIENE: MDental Láser --> mdentalaser@gmail.com
YA TIENE: Dora Álvarez --> doraalvarezodontologia@gmail.com
Focus Dental Center Odontología --> sin email
YA TIENE: Dental Specialists Medellín --> contact@dentalmedellin.com
Jenny Villada Clínicas Odontológicas --> sin email
YA TIENE: Smile Dental Center Medellín | Carillas Dentales y Diseño de Sonrisa --> info@smiledentalcentergroup.com
Clinica odontologica Dra Vanessa Corrales --> sin email
Ortodoncia Dental Medellin --> sin email
YA TIENE: Lina Fernández Odontología - Diseño de sonrisa y Blanqueamiento dental en Medellín --> linafernandezodontologia@gmail.com
YA TIENE: CLINICA DENTAL POBLADO --> dental-poblado@hotmail.com
YA TIENE: Clínica Dental Home --> info@clinicadentalhome.net
YA TIENE: Odontología OPAL - DISEÑO DE SONRISA - CORONAS DENTALES --> contact@mysite.com
Syma Clínica Odontológica --> sin email
YA TIENE: Beaming Dental Clinic | Clínica dental en Colombia --> beaming.smiledesign@gmail.com
YA TIENE: ODONTOLOGÍA Y ORTODONCIA MEDELLIN - ORALCOMPANY --> info@oralcompany.org
YA TIENE: Orthoarte Poblado --> info@orthoarte.com
Dental Planet Odontopediatria --> sin email
Odontólogo Ces --> sin email
Colmédica Medellin El Poblado - Centro Médico y Odontológico - Oficina --> sin email
Odontología Especializada Medellín --> sin email
YA TIENE: Turismo Dental Colombia - Dr. Camilo Aguirre --> user@domain.com
Clínica Odontológica PROMTA - Sede Poblado --> sin email
Dental Expertos --> sin email
ORAL CONCEPT INVISALIGN --> sin email
YA TIENE: Ortodoncia Funcional CG --> info@ortodonciafuncional.com
YA TIENE: Clínica Dental Home --> info@clinicadentalhome.net
YA TIENE: Hi Dental IPS --> hidentalservicioalcliente@gmail.com
YA TIENE: Odontoss Laureles --> gerencia@odontoss.com
LaborDental Laureles --> sin email
YA TIENE: Alta Estetica Dental Laureles --> asesoria@altaesteticadental.com.co
Consultorio odontológico Smiley --> sin email
ORAL MAS ESPECIALISTAS --> sin email
Infinity Smile --> sin email
Dra Juliana Fernández J --> sin email
Dra Liliana Gutiérrez L. --> sin email
YA TIENE: Consultorio odontologico la 73 --> odontologosla73@gmail.com
Sanadent Odontólogos - La Mejor Clínica Dental en Medellín --> sin email
Luminux Odontología Integral y Estética, Laureles --> sin email
Odontología la 78 Urgencia las 24 horas --> contact@mysite.com
Neodental Centro Odontológico Laureles --> sin email
Dr. Mauricio Arias - Odontólogo Experto en Medellín English Dentist --> sin email
YA TIENE: Oralimagen --> siev@siev.com.co
Odontologos en Medellin --> info@odontologoenmedellin.com
Centro Odontológico Orthoplan Laureles --> sin email
Paula Ramírez Consultorio Odontológico --> sin email
Oral + ortodoncia --> sin email
YA TIENE: Camila Paredes Odontología --> soporte@doctoralia.com
YA TIENE: Casa De Sonrisas --> info@casadesonrisas.co
Alternativas Odontológicas --> sin email
YA TIENE: Centro Aliado Moons Laureles --> hola@moonsdental.com
CLÍNICA DENTAL ALEGRA SEDE LAURELES --> sin email
Centro Odontológico White Dental --> sin email
YA TIENE: Dentix Laureles --> %20atencionalpaciente@dentix.co
WS Medellin - ODONTOLOGIA ESTETICA ESPECIALIZADA --> sin email
OdontoestéticaDH --> proyectoweber+odontoesteticadh.com@gmail.com
YA TIENE: Teran Florez Odontología Especializada --> you@website.com
Mastic Odontología --> sin email
Naturaldent --> sin email
YA TIENE: Innova Odontologos Especialistas --> info@innovaoe.com
URGENCIAS ODONTOLOGICAS, MEDELLÍN --> sin email
Ortoclin Sede Laureles --> sin email
Oral Center Distrito 65 --> sin email
Dental Exclusive --> sin email
YA TIENE: DentiSalud Floresta - Clínica odontológica --> info@dentisalud.com.co
Dento Grupo Odontológico --> sin email
Natural odontología --> sin email
YA TIENE: Clínica Colombiana de Implantes Dentales --> mercadeo@clinicacolombianadeimplantes.com
Dr. JAIME VARGAS Consultorio Odontológico 211 --> sin email
Nova Dental Studio --> sin email
Trébol Odontología Especializada Medellín --> sin email
Dra Tamayo Centro Odontológico --> sin email
Ortoclin Sede Santa Lucia --> sin email
YA TIENE: Clínica Odontológica Oral Laser Estadio --> Mesa-de-trabajo-175@150x-100-10.jpg
Ópalo Odontología Estética --> sin email
Odontólogos y Especialistas --> sin email
Happy Dental --> sin email
Ortoclin Sede Floresta --> sin email
YA TIENE: Dentales Antioquia S.A.S --> john-doe@email.com
CERO 70 SAS - Sede Laureles --> sin email
Centro Integral de Salud Oral Los Laureles --> sin email
Clínica Odontológica Punto Oral S.A --> sin email
YA TIENE: IPS Odontología San Juan --> jaimeorregogarcia@gmail.com
ODONTOLOGIA EL NOGAL --> sin email
Space. Centro radiológico oral cero 70, la 33 --> sin email
YA TIENE: Sonría --> analistavozdelcliente@sonria.com.co
ORAL-TEC --> sin email
True Smile Clinica odontologica en Envigado --> sin email
YA TIENE: Marr Dental - Clínica odontológica en Medellín --> bg-vertical-tabs@2x.png
Unidad Médica Odontológica - Odontología Especializada --> sin email
YA TIENE: Prevenga Odontología Particular - Envigado --> info@clinicasprevenga.com
YA TIENE: Clinica Odontológica Oral Laser Envigado --> Mesa-de-trabajo-175@150x-100-10.jpg
OdontoSur Clínica --> sin email
YA TIENE: NaturalDent Envigado --> ajax-loader@2x.gif
Ortoclin Sede Envigado --> sin email
LK Dental Odontología General y Especializada en Envigado | Diseño de Sonrisa --> sin email
YA TIENE: Clínica Odontológica Dra. Paula Muñoz. --> odontoestetic207@gmail.com
Odox clínica odontológica envigado --> sin email
Odontología Dental Bliss - Sede Envigado --> sin email
Centro Odontológico Clean Smile --> sin email
Odontologo en Envigado Dra. Edith Ofelia Pardo --> sin email
32 rocks, clinica dental envigado --> sin email
Consultorio Odontologico El Dorado --> sin email
YA TIENE: Odontología Especializada El Escobero Envigado Dra. Yamile Atehortua --> yamileodonto@gmail.com
Consultorio Odontológico Carolina Herrera --> sin email
Olivo Odontologia --> sin email
CENTRO ODONTOLOGICO DE ANTIOQUIA --> sin email
CEO - Centro Estético Odontológico --> sin email
YA TIENE: Dra. Jessica Londoño --> ajax-loader@2x.gif
Juliana Rojas Odontología --> sin email
lets smile envigado --> sin email
YA TIENE: SMILE Clínica Odontológica sede Envigado --> mercadeo@grupoodontologicosmile.com.co
YA TIENE: Dentalix Clinic --> contacto@dentalixclinic.com
Consultorio Odontológico Gilma Garcia --> sin email
Innova Dental Odontología --> sin email
Odontología Sara Restrepo Vélez --> sin email
Smile Odontólogos --> sin email
Odontolam, Odontológos Especialistas --> sin email
YA TIENE: Envigado Dental Design Dr. Hugo Sánchez --> dentaldesign.mercadeo@gmail.com
Consultorio Odontológico Odontología Familiar --> sin email
OdontoSonrisasenvigado --> sin email
Envigado Oral --> sin email
YA TIENE: COA-Centro Oncológico de Antioquia --> informacion.coa@quironsalud.com
YA TIENE: Odontoexpertos envigado --> mercadeoodontoexpertos@gmail.com
OdontoZane --> sin email
Dentus Odontologia Integral --> sin email
ALMA DENTAL --> sin email
AllDent Odontología Especializada --> sin email
Odontologo Daniel Restrepo Salazar --> sin email
Urgencias Odontológicas 24 horas las Vegas --> sin email
CERO 70 SAS - Sede Envigado --> sin email
Clinica de Implantes Dentales del Sur --> sin email
PARA ODONTÓLOGOS S.A.S. --> sin email
Dra. Angela María Tamayo Posada --> sin email
magna clínica dental --> sin email
Bucco "Odontología De Alto Nivel" --> sin email
YA TIENE: ORTODIAGNOSTICO --> ortodx@une.net.co
Dra.Patricia Alvarez Gomez --> sin email
YA TIENE: Angela Guevara Odontología Integrativa --> angelamariarehabilitadoraoral@gmail.com
CENTRO ODONTOLOGICO ASDENTAL --> sin email
Consultorio Odontológico (Anteriormente Esmar Odontología Especializada) --> sin email
CEROMA --> sin email
YA TIENE: Consultorio Odontológico OC --> info@clinicaoc.com.co
Stetika Odontologia --> sin email
YA TIENE: Vivartec - Odontología --> vivartecdental@gmail.com
Dentotal --> sin email
YA TIENE: Odontología Especializada | Dra. Libia Espinosa --> contacto@ejemplo.com
Centro Especializado Odontológico --> sin email
Oral Center Bello --> sin email
Smile Me --> sin email
Centro Odontológico Integral Maxsy --> sin email
YA TIENE: Punto Odontológico --> juan1david2@gmail.com
Consultorio Odontológico Avenida --> sin email
Consultorio y laboratorio dental Jesús Arroyave (Dra. Lisbeth Velasquez) --> sin email
Odonto Innova --> sin email
YA TIENE: Dra. Astrix Vivas | Odontología general y estética --> consul24draastrixvivas@gmail.com
YA TIENE: Dra. Libia Espinosa S --> contacto@ejemplo.com
Dental line --> sin email
CONSULTORIO ODONTOLOGICO Y LABORATORIO DENTAL SAN JOSE --> sin email
Centro Odontológico la Cabaña --> sin email
Odontología Jorge García S.A.S --> sin email
YA TIENE: Hidental IPS Sede Bello --> hidentalservicioalcliente@gmail.com
ODONTOINSUMOS --> sin email
Dent Sonrisas Centro Odontologico --> sin email
Oraldent --> sin email
Consultorio Odontologíco Somos Dental --> sin email
Odontoclave Bello Fabricato --> sin email
Biodent Centro odontológico --> sin email
Hola Odontología --> sin email
Oralis Odontologia + Estetica --> name@emailaddress.com
Kdent --> sin email
Comfama Bello Sede Centro --> seguridadti@comfama.com.co
Medibello --> sin email
Consultorio Odontológico Angela Maria Rodriguez --> sin email
Consultorio Odontológico Maxident --> sin email
Super Sonrisas (sede cabañas) --> sin email
Tu Salud Oral Clínica Dental --> sin email
Maxi Sonrisas --> sin email
Centro Odontológico Camilo Gallego Zea --> sin email
Cuidarte Clínicas Odontológicas --> sin email
Arte y Boca Niquia --> sin email
Dental Solution --> sin email
Centro Ejecutivo Cristal --> sin email
Oficentro --> sin email
YA TIENE: MYM odontología --> ortodoncia@4x.png
YA TIENE: Oral Medic --> citas@oralmedicips.com
Ortolife --> sin email
ODONTOCLAVE FABRICATO --> sin email
ESE Bellosalud Rosalpi --> sin email
Consultorio Y Laboratorio Odontológico San Ignacio --> sin email
YA TIENE: Centro comercial Parque Fabricato --> recepcionistafabricato@parauco.com
Super Smile --> sin email
YA TIENE: Prevenga Odontología Particular - Itagüí --> info@clinicasprevenga.com
estilo Oral --> sin email
YA TIENE: Clínica Odontológica Oral Laser Itagüi --> Mesa-de-trabajo-175@150x-100-10.jpg
Espacio Dental --> sin email
Oral Sonrie --> sin email
YA TIENE: Odontoss Itagui --> gerencia@odontoss.com
Consultorio Odontológico El Carmelo --> sin email
Dr. Andrés Fuertes odontología ética y responsable. --> sin email
DentiSalud Itagui --> sin email
YA TIENE: URGENCIAS ODONTOLÓGICAS ITAGÜÍ --> cliente@gurusoluciones.com
Dentiplan Itagüí --> sin email
YA TIENE: Odontologos Santamaria --> odontologiaudeasantamaria@gmail.com
Urgencias Odontologicas del Sur --> sin email
Consultorio odontológico gdental --> sin email
Centro De Radiologia Oral Jg Itagüi --> sin email
MP ODONTOLOGÍA --> sin email
Clínica Odontologica Mundo Sonrisas --> sin email
Élite Smile --> sin email
Odontología en itagui Dra. Alejandra Ruiz Uribe --> sin email
Consultorio Odontólogico Dra Lady Castaño --> sin email
YA TIENE: Consultorio odontológico Dr Anderson Echeverry --> info@doctorandersonecheverryv.com
DENTSONRISAS --> sin email
YA TIENE: Natural Dent Itagui --> ajax-loader@2x.gif
Consultorio Odontológico Biodental HH --> sin email
Dentali odontología - Sede Itagüí --> gerenteoperativa@dentali.com.co
YA TIENE: Natural Concept Odontólogos --> informacion@naturalconcept.com.co
CS&CS Salud Oral y Piel --> sin email
Odontología Segura --> sin email
Dr DNY Odontología Sabaneta --> sin email
Dental Clinique --> sin email
Consultorio Odontologico Dr. Freiman Alvarez --> sin email
Innovarte Dental --> sin email
Diagnostico Digital --> sin email
Odontología - Dientes Sanos Itagüí --> sin email
DENTAL CLINIC GRUPO ODONTOLOGICO --> sin email
Centro Comercial La Gran manzana --> centroccialgm2@gmail.com
YA TIENE: ODONTOLOGIA INTEGRAL --> contacto@odontologiaintegral.co
Odontics Sabaneta --> sin email
Odontologia Integral Itagui --> sin email
Consultorio Odontólogico El Buen Samaritano --> sin email
YA TIENE: 360 Dental Group IPS | Clínica Odontológica Mayorca --> administracion@sonrisas360.com
YA TIENE: Clínica Total Harmony - Dr. Edison Giraldo --> hello@mail.com
YA TIENE: Dra. Lisbed Giraldo Olarte, Odontólogo --> soporte@doctoralia.com
La Feria Dental --> sin email
YA TIENE: Maxdentall --> maxdentallinfo@gmail.com
Santa Teresita Centro Odontológico --> sin email
Consultorio Odontológico Clara Sonrisa --> sin email
Centro Odontológico Estética Dental --> sin email
Centro Comercial y empresarial Itagüí Plaza --> sin email
Odontologa Eliana Gomez --> sin email
Clinica Odontológica Orthodox Mayorca --> sin email
YA TIENE: Odontoespecialistas --> gerencia@odontoespecialistas.com
YA TIENE: Odontología The Best Smile Centro Medellín --> thebestsmileod@gmail.com
Centro Odontológico San Martin --> sin email
Centro Radiológico Oral Centro de Medellin --> sin email
YA TIENE: Clínica Odontologica Oral Centro --> oralcentro86@gmail.com
YA TIENE: Ortounion Clínica Odontológica --> info@ortounion.com
YA TIENE: Clínica Odontológica Oral Laser Centro --> Mesa-de-trabajo-175@150x-100-10.jpg
YA TIENE: Odontoss Centro --> gerencia@odontoss.com
Bocas&Risas - Clínica Odontológica en Medellín --> sin email
Oral Elite Consultorio Odontológico atendido por el Dr Alejandro Ramírez --> sin email
CERO70 SAS - Sede Centro --> sin email
Consultorio Odontológico Vida Oral --> sin email
CENTRO DENTAL LA ESPERANZA --> sin email
CM Odontología --> sin email
YA TIENE: Centro Médico Buenos Aires --> cmbuenosaires2@gmail.com
centroral --> sin email
Odontología Ana María Martínez --> sin email
Ana Virgen Smile --> sin email
Sanadent --> sin email
Másdental Sede San Diego --> sin email
DIENTES SANOS MEDELLIN --> sin email
YA TIENE: DentiOral - Sede Belén --> info@dentioral.com
Centro Odontológico Congregación Mariana --> sin email
centro odontologico la 65 --> sin email
YA TIENE: Clínica Odontológica de Antioquia - CLODAN sas. --> nosinspiras@clodan.com.co
Odonto Rio - Estudio Dental --> sin email
Centro Odontológico La Oriental --> sin email
Sede Centro - PROMTA Clínica Odontológica --> sin email
YA TIENE: Consultorio odontológico Angela Zapata --> os.com@gmail.com
Centro Comercial El Punto de La Oriental --> sin email
StarNova Consultorio Odontologico By Juan Pablo Lopera --> Contacto@starnova.co
ORAL DESIGN CENTRO --> sin email
Dens Clinicas Dentales --> sin email
Dental clinic soluciones odontologicas --> sin email
CREADENTISS, odontología integral --> sin email
CIO Clínica Dental --> sin email
dr perfect smile sabaneta --> sin email
Tooth Dentistry --> sin email
YA TIENE: Odontoss Sabaneta --> gerencia@odontoss.com
OralZen --> sin email
orthowhite sabaneta --> sin email
YA TIENE: Deluxe Smile --> deluxesmiledental@gmail.com
All Smiles Odontología --> sin email
Consultorio Odontologico Dr. Juan Fernando Acevedo Vergara --> sin email
odontomaster --> sin email
Javier Vanegas Odontólogos Especialistas --> sin email
Santé - Odontología Integral --> sin email
Radiológica Diagnóstico oral --> sin email
Eliana Yepes - Consultorio Odontológico --> sin email
Luminux Odontología, Sabaneta --> sin email
Fenixia Dental Art Odontología --> sin email
Odontoclave Mayorca --> sin email
YA TIENE: Dental Miracle --> odontologia.dentalmiracle@gmail.com
SMILE Clínica Odontológica sede Sabaneta --> sin email
Mundo oral --> sin email
Odontologia Armonize --> sin email
CERO 70 SAS - Sede Sabaneta --> sin email
Centro Dental Dr Gabriel Hurtado --> sin email
Odontología 30a --> sin email
YA TIENE: Dental Master - Dr. Rubén Arbeláez --> masterdentalsas@gmail.com
YA TIENE: Odontocer, Centro de Estética y Rehabilitación Oral --> comunicaciones@odontocer.com
Neodental Centro Odontológico --> sin email
Dr Andres Alvarez Implantologo oral y Rehabiltacion --> sin email
San José Centro Odontológico --> sin email
YA TIENE: Odontorisas --> consultas@odontorisas.com
Orthodontics Medellín --> sin email
YA TIENE: Clinica Dental Sonría BELÉN --> analistavozdelcliente@sonria.com.co
Clínica Odontológica Dientes Sanos Belén --> sin email
SONRIESTHETIC ODONTOLOGÍA --> sin email
ProSmile Medellín - Expertos en Salud Bucal y Estética Dental --> sin email
Odontologia Integral OdontoVitha, Profesionales independientes --> sin email
Centro Odontologico Bulerias --> sin email
Esencia Dental --> sin email
ORAL DESIGN - DISEÑO DE SONRISA - VENEERS --> sin email
Clínica Dental - Belén Dental --> sin email
Dental smile laboratorio --> sin email
Clinica Menta --> sin email
Dental House --> sin email
Dental Team - SEDE BELÉN (PLAZOLETA NUEVA VILLA DEL ABURRÁ) --> sin email
Ortho Estetika --> sin email
Consultorio y laboratorio odontológico Robledo --> sin email
Centro Odontológico Especializado CARDENT --> sin email
Consultorio Robledo Odontología Integral --> sin email
Consultorio odontológico Oral Life Odontología Integral --> sin email
Consultorio Odontologico Robledo --> sin email
Centro odontologico vital Dent --> sin email
Mirando Sonrisas - Urgencias Odontologicas --> sin email
Centro Odontologico Robledo --> sin email
Centro Médico y Odontológico La 75 --> sin email
MEDICINA-ODONTOLOGÍA LABORATORIO CLÍNICO --> sin email
Ortoclin Sede Castilla --> sin email
Odontologia Integral Castilla --> sin email
SALUD ORAL CENTER I.P.S S.A.S --> sin email
Dentali odontología - Sede Castilla --> gerenteoperativa@dentali.com.co
YA TIENE: Armony Dental --> armonydentalmedellin@gmail.com
JKDENTAL --> sin email
ORAL PLUS Odontología Integral --> sin email
Consultorio Odontologico Daniela Ruiz Sanchez --> sin email
Odontovital Tricentenario --> sin email
Consultorio Odontológico - Miguel Uribe --> sin email
consultorio odontologíco --> sin email
Urgencia Odontologicas Castilla --> sin email
Abba Dent --> sin email
Laboratorio dental --> sin email
MJ Odontología Integral --> sin email
Odontología Especializada --> sin email
Odontología Aranjuez --> sin email
RxNortDental --> sin email
Odontología OVA --> sin email

Total emails: 110 de 375

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,,centros odontologicos El Poblado Medellin
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,,centros odontologicos El Poblado Medellin
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin
...,...,...,...,...,...,...,...
370,MJ Odontología Integral,"Cl. 91A # 71 - 30 int 301, Francisco Zea, Mede...",305 3818475,NaN,3.0,,centros odontologicos Castilla Medellin
371,Odontología Especializada,"Cl. 57 #49-44, La Candelaria, Medellín, La Can...",333 2922519,NaN,5.0,,centros odontologicos Castilla Medellin
372,Odontología Aranjuez,"Cra. 49A #92-90, Aranjuez, Medellín, Aranjuez,...",310 8388449,https://wa.me/573108388449,4.9,,centros odontologicos Castilla Medellin
373,RxNortDental,"CC Terminal del Norte, Local 156, Oleoducto, M...",NaN,NaN,3.4,,centros odontologicos Castilla Medellin
374,Odontología OVA,"Castilla, Medellín, Castilla, Medellín, Antioq...",NaN,NaN,NaN,,centros odontologicos Castilla Medellin

In [28]:
import requests
import pandas as pd
import time

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"

df_existente = pd.read_excel("leads_odontologos_medellin_completo.xlsx")

zonas = [
    "centros odontologicos El Poblado Medellin",
    "centros odontologicos Laureles Medellin",
    "centros odontologicos Envigado",
    "centros odontologicos Bello",
    "centros odontologicos Itagui",
    "centros odontologicos Centro Medellin",
    "centros odontologicos Sabaneta",
    "centros odontologicos Belen Medellin",
    "centros odontologicos Robledo Medellin",
    "centros odontologicos Castilla Medellin"
]

# Guardar place_ids existentes si ya tiene esa columna
if "place_id" in df_existente.columns:
    ids_vistos = set(df_existente["place_id"].dropna().tolist())
else:
    ids_vistos = set()

nuevos_ids = []

for zona in zonas:
    params = {"query": zona, "key": API_KEY, "language": "es"}
    while True:
        response = requests.get(url_search, params=params).json()
        for place in response.get("results", []):
            place_id = place.get("place_id", "")
            nuevos_ids.append({
                "Nombre": place.get("name", ""),
                "place_id": place_id
            })
        next_page_token = response.get("next_page_token")
        if next_page_token:
            time.sleep(3)
            params = {"pagetoken": next_page_token, "key": API_KEY}
        else:
            break

# Agregar place_id al Excel existente haciendo match por nombre
df_ids = pd.DataFrame(nuevos_ids).drop_duplicates(subset="Nombre")
df_final = df_existente.merge(df_ids, on="Nombre", how="left")
df_final.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"place_id agregado a {df_final['place_id'].notna().sum()} de {len(df_final)} registros")
df_final

KeyError: 'place_id'

In [29]:
# Ver columnas que tiene el Excel actualmente
df_existente = pd.read_excel("leads_odontologos_medellin_completo.xlsx")
print(df_existente.columns.tolist())

['Nombre', 'Direccion', 'Telefono', 'Web', 'Rating', 'Email', 'Zona', 'place_id_x', 'place_id_y']

In [30]:
import pandas as pd

df = pd.read_excel("leads_odontologos_medellin_completo.xlsx")

# Combinar las dos columnas en una sola
df["place_id"] = df["place_id_x"].fillna(df["place_id_y"])

# Eliminar las columnas duplicadas
df = df.drop(columns=["place_id_x", "place_id_y"])

df.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"place_id agregado a {df['place_id'].notna().sum()} de {len(df)} registros")
print(df.columns.tolist())
df

place_id agregado a 355 de 375 registros
['Nombre', 'Direccion', 'Telefono', 'Web', 'Rating', 'Email', 'Zona', 'place_id']

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona,place_id
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,NaN,centros odontologicos El Poblado Medellin,ChIJX2o-xYGCRo4Rn6L7wacsRJo
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin,ChIJgwmJfiYoRI4RvO8goH3oe7M
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,NaN,centros odontologicos El Poblado Medellin,ChIJc8AO2KUpRI4R5lZzeBklf3U
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin,ChIJ42xK_4kpRI4RwY-W14dE_BU
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin,ChIJN3fIPZ8pRI4RytlAMwH5Zuw
...,...,...,...,...,...,...,...,...
370,MJ Odontología Integral,"Cl. 91A # 71 - 30 int 301, Francisco Zea, Mede...",305 3818475,NaN,3.0,NaN,centros odontologicos Castilla Medellin,NaN
371,Odontología Especializada,"Cl. 57 #49-44, La Candelaria, Medellín, La Can...",333 2922519,NaN,5.0,NaN,centros odontologicos Castilla Medellin,ChIJZ45MIQApRI4Rkq8Ou7UWmFw
372,Odontología Aranjuez,"Cra. 49A #92-90, Aranjuez, Medellín, Aranjuez,...",310 8388449,https://wa.me/573108388449,4.9,NaN,centros odontologicos Castilla Medellin,ChIJAWOkslYpRI4RFe5kqOuwLRM
373,RxNortDental,"CC Terminal del Norte, Local 156, Oleoducto, M...",NaN,NaN,3.4,NaN,centros odontologicos Castilla Medellin,NaN
374,Odontología OVA,"Castilla, Medellín, Castilla, Medellín, Antioq...",NaN,NaN,NaN,NaN,centros odontologicos Castilla Medellin,ChIJ2wRYUiovRI4R_QiHvy35oOY

In [31]:

import requests
import pandas as pd

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
df = pd.read_excel("leads_odontologos_medellin_completo.xlsx")

# Filtrar los que no tienen place_id
sin_id = df[df["place_id"].isna()]
print(f"Registros sin place_id: {len(sin_id)}")

for i, row in sin_id.iterrows():
    try:
        params = {
            "query": row["Nombre"] + " Medellin",
            "key": API_KEY,
            "language": "es"
        }
        response = requests.get(
            "https://maps.googleapis.com/maps/api/place/textsearch/json",
            params=params
        ).json()
        
        results = response.get("results", [])
        if results:
            df.at[i, "place_id"] = results[0].get("place_id", "")
            print(f"OK: {row['Nombre']}")
        else:
            print(f"No encontrado: {row['Nombre']}")
    except:
        print(f"Error: {row['Nombre']}")

df.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"\nplace_id total: {df['place_id'].notna().sum()} de {len(df)}")

Registros sin place_id: 20
OK: Ortoclin Sede Floresta
OK: ODONTOLOGIA EL NOGAL
OK: Space. Centro radiológico oral cero 70, la 33
OK: Sonría
OK: ORAL-TEC
OK: Vivartec - Odontología
OK: ORAL DESIGN CENTRO
OK: ORAL DESIGN - DISEÑO DE SONRISA - VENEERS
OK: Clínica Dental - Belén Dental
OK: Dental smile laboratorio
OK: Clinica Menta
OK: Dental House
OK: Dental Team - SEDE BELÉN (PLAZOLETA NUEVA VILLA DEL ABURRÁ)
OK: Ortho Estetika
OK: Mirando Sonrisas - Urgencias Odontologicas
OK: Armony Dental
OK: Consultorio Odontologico Daniela Ruiz Sanchez
OK: Laboratorio dental
OK: MJ Odontología Integral
OK: RxNortDental

place_id total: 375 de 375

In [32]:
import pandas as pd
import re

df = pd.read_excel("leads_odontologos_medellin_completo.xlsx")

def extraer_whatsapp(web, telefono):
    if web and not pd.isna(web):
        wa = re.findall(r'wa\.me/(\d+)', str(web))
        if wa:
            return "+" + wa[0]
    if telefono and not pd.isna(telefono):
        numero = re.sub(r'\D', '', str(telefono))
        if numero.startswith('3') and len(numero) == 10:
            return "+57" + numero
        if numero.startswith('573') and len(numero) == 12:
            return "+" + numero
    return ""

df["WhatsApp"] = df.apply(
    lambda row: extraer_whatsapp(row.get("Web"), row.get("Telefono")), axis=1
)

df.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"WhatsApp encontrados: {df['WhatsApp'].ne('').sum()} de {len(df)}")
df

WhatsApp encontrados: 269 de 375

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona,place_id,WhatsApp
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,NaN,centros odontologicos El Poblado Medellin,ChIJX2o-xYGCRo4Rn6L7wacsRJo,
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin,ChIJgwmJfiYoRI4RvO8goH3oe7M,
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,NaN,centros odontologicos El Poblado Medellin,ChIJc8AO2KUpRI4R5lZzeBklf3U,+573146628875
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin,ChIJ42xK_4kpRI4RwY-W14dE_BU,+573246027040
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin,ChIJN3fIPZ8pRI4RytlAMwH5Zuw,+573011795872
...,...,...,...,...,...,...,...,...,...
370,MJ Odontología Integral,"Cl. 91A # 71 - 30 int 301, Francisco Zea, Mede...",305 3818475,NaN,3.0,NaN,centros odontologicos Castilla Medellin,ChIJQROjti8pRI4Rqo8MLFrlSiw,+573053818475
371,Odontología Especializada,"Cl. 57 #49-44, La Candelaria, Medellín, La Can...",333 2922519,NaN,5.0,NaN,centros odontologicos Castilla Medellin,ChIJZ45MIQApRI4Rkq8Ou7UWmFw,+573332922519
372,Odontología Aranjuez,"Cra. 49A #92-90, Aranjuez, Medellín, Aranjuez,...",310 8388449,https://wa.me/573108388449,4.9,NaN,centros odontologicos Castilla Medellin,ChIJAWOkslYpRI4RFe5kqOuwLRM,+573108388449
373,RxNortDental,"CC Terminal del Norte, Local 156, Oleoducto, M...",NaN,NaN,3.4,NaN,centros odontologicos Castilla Medellin,ChIJM42n9t4pRI4RiGI30dZkmhk,
374,Odontología OVA,"Castilla, Medellín, Castilla, Medellín, Antioq...",NaN,NaN,NaN,NaN,centros odontologicos Castilla Medellin,ChIJ2wRYUiovRI4R_QiHvy35oOY,

In [33]:
import requests
import pandas as pd
import time
import re

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"
url_details = "https://maps.googleapis.com/maps/api/place/details/json"

# Cargar base existente
df_existente = pd.read_excel("leads_odontologos_medellin_completo.xlsx")
ids_vistos = set(df_existente["place_id"].dropna().tolist())

# Zonas nuevas
zonas_nuevas = [
    "centros odontologicos Buenos Aires Medellin",
    "centros odontologicos Manrique Medellin",
    "centros odontologicos Aranjuez Medellin"
]

nuevos_leads = []

def extraer_email(url):
    if not url or pd.isna(url):
        return ""
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=8)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', response.text)
        emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example'])]
        return emails[0] if emails else ""
    except:
        return ""

def extraer_whatsapp(web, telefono):
    if web and not pd.isna(web):
        wa = re.findall(r'wa\.me/(\d+)', str(web))
        if wa:
            return "+" + wa[0]
    if telefono and not pd.isna(telefono):
        numero = re.sub(r'\D', '', str(telefono))
        if numero.startswith('3') and len(numero) == 10:
            return "+57" + numero
        if numero.startswith('573') and len(numero) == 12:
            return "+" + numero
    return ""

for zona in zonas_nuevas:
    print(f"\nBuscando: {zona}")
    params = {"query": zona, "key": API_KEY, "language": "es"}
    
    while True:
        response = requests.get(url_search, params=params).json()
        
        for place in response.get("results", []):
            place_id = place.get("place_id", "")
            
            if place_id in ids_vistos:
                print(f"Duplicado: {place.get('name')}")
                continue
            ids_vistos.add(place_id)
            
            details = requests.get(url_details, params={
                "place_id": place_id,
                "fields": "formatted_phone_number,website",
                "key": API_KEY
            }).json()
            
            web = details.get("result", {}).get("website", "")
            telefono = details.get("result", {}).get("formatted_phone_number", "")
            email = extraer_email(web)
            whatsapp = extraer_whatsapp(web, telefono)
            
            nuevos_leads.append({
                "Nombre": place.get("name", ""),
                "Direccion": place.get("formatted_address", ""),
                "Telefono": telefono,
                "Web": web,
                "Rating": place.get("rating", ""),
                "Email": email,
                "Zona": zona,
                "place_id": place_id,
                "WhatsApp": whatsapp
            })
            print(f"OK: {place.get('name')}")
        
        next_page_token = response.get("next_page_token")
        if next_page_token:
            time.sleep(3)
            params = {"pagetoken": next_page_token, "key": API_KEY}
        else:
            break

# Unir con la base existente
df_nuevos = pd.DataFrame(nuevos_leads)
df_final = pd.concat([df_existente, df_nuevos], ignore_index=True)
df_final.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"\nNuevos leads agregados: {len(nuevos_leads)}")
print(f"Total base de datos: {len(df_final)}")
df_final

Buscando: centros odontologicos Buenos Aires Medellin
Duplicado: Centro Médico Buenos Aires
Duplicado: Premium Dental Medellín
OK: ODONTOLOGÍA NOVA
Duplicado: Dental Center
OK: Centro Odontológico
OK: Ortoclin Sede Buenos Aires
Duplicado: Bocas&Risas - Clínica Odontológica en Medellín
OK: Estacion Oral
OK: Consultorio Odontologico Maria Luisa Ledezma - Urgencias Odontologicas
Duplicado: Dr. Mauricio Arias - Odontólogo Experto en Medellín English Dentist
OK: Dental By
Duplicado: Clínica Odontológica Oral Laser Centro
OK: Servicio Odontológico Cl49
Duplicado: Odontología Aranjuez
Duplicado: Focus Dental Center Odontología
OK: Odontologia Buenos Aires
Duplicado: Oral Studio
OK: International Smiles
OK: Centro Odontológico Estético
Duplicado: Oral Center Poblado
Duplicado: Odonto Rio - Estudio Dental

Buscando: centros odontologicos Manrique Medellin
OK: Dental Force Manrique
OK: Centro Médico y Odontologico Clásico
OK: Sonríes Odontología Especializada
OK: Odontología La 41
OK: Consultorio Odontologico
OK: Dentimed
OK: Consultorio Odontologico Dr. CARLOS BERRIO
OK: Diagnostic Oral
OK: ODONTOLOGIA GENERAL
OK: Consultorio Odontologico La 92
OK: Consultorio Odontológico Dentalov
Duplicado: Odontología Aranjuez
OK: Unidad Hospitalaria Manrique "Hermenegildo De Fex"
OK: ODONTOLOGIA INTEGRAL
Duplicado: Bocas&Risas - Clínica Odontológica en Medellín
OK: Gardel Plaza Centro Comercial
OK: Odontología intégral Palos verdes
OK: Dentali odontología - Sede Aranjuez
OK: SpecialistDent
OK: Consultorio Odontológico Las Granjas

Buscando: centros odontologicos Aranjuez Medellin
Duplicado: Odontología Aranjuez
Duplicado: Consultorio Odontológico Dentalov
OK: Happy Dental
Duplicado: Consultorio Odontologico La 92
OK: Consultorio Odontológico Vita
Duplicado: Dentimed
OK: Odontovaldés
Duplicado: Dentali odontología - Sede Aranjuez
OK: Consultorio Odontológico Berlín
OK: Consultorio Odontologico El Bosque
OK: Dentalov Dr Mauricio Toro
OK: Smart Dental Group
Duplicado: Consultorio Odontologico
OK: Consultorio Odontológico S.l.S Aranjuez
Duplicado: Odontólogos y Especialistas
Duplicado: Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín
Duplicado: Dental Force Manrique
Duplicado: Happy Dental
Duplicado: Focus Dental Center Odontología
Duplicado: Clínica Dental Home
OK: Proinsa odontología sede San Isidro

PermissionError: [Errno 13] Permission denied: 'leads_odontologos_medellin_completo.xlsx'

In [34]:
df_final.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"\nNuevos leads agregados: {len(nuevos_leads)}")
print(f"Total base de datos: {len(df_final)}")
df_final

Nuevos leads agregados: 37
Total base de datos: 412

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona,place_id,WhatsApp
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,NaN,centros odontologicos El Poblado Medellin,ChIJX2o-xYGCRo4Rn6L7wacsRJo,NaN
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin,ChIJgwmJfiYoRI4RvO8goH3oe7M,NaN
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,NaN,centros odontologicos El Poblado Medellin,ChIJc8AO2KUpRI4R5lZzeBklf3U,573146628875.0
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin,ChIJ42xK_4kpRI4RwY-W14dE_BU,573246027040.0
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin,ChIJN3fIPZ8pRI4RytlAMwH5Zuw,573011795872.0
...,...,...,...,...,...,...,...,...,...
407,Consultorio Odontologico El Bosque,"Cl. 80c #52-48, Aranjuez, Medellín, Aranjuez, ...",,,5,,centros odontologicos Aranjuez Medellin,ChIJYS-ib9soRI4Rmsc4Ab7rEi8,
408,Dentalov Dr Mauricio Toro,"Cra. 51 #91-17, Aranjuez, Medellín, Aranjuez, ...",318 5781173,,5,,centros odontologicos Aranjuez Medellin,ChIJ18uyOjopRI4RDfpIemTnf84,+573185781173
409,Smart Dental Group,"Cl. 73 #51D- 71 local 1013, Aranjuez, Medellín...",316 3146519,http://www.smartdentalgroup.co/,4.4,,centros odontologicos Aranjuez Medellin,ChIJKzHA4kYpRI4RTHpY-giVNH0,+573163146519
410,Consultorio Odontológico S.l.S Aranjuez,"Cra. 50 #92-21 Piso 2, Aranjuez, Medellín, Ara...",304 5246460,https://www.instagram.com/consultorioodontolog...,,,centros odontologicos Aranjuez Medellin,ChIJqXiRuUUpRI4Rg3AZahcTGYo,+573045246460
411,Proinsa odontología sede San Isidro,"Cra. 52 #95-91, Aranjuez, Medellín, Aranjuez, ...",316 8772932,,2.5,,centros odontologicos Aranjuez Medellin,ChIJhaYDZC8pRI4RXGYO2E-GNSg,+573168772932

In [35]:
import requests
import pandas as pd
import time
import re

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"
url_details = "https://maps.googleapis.com/maps/api/place/details/json"

df_existente = pd.read_excel("leads_odontologos_medellin_completo.xlsx")
ids_vistos = set(df_existente["place_id"].dropna().tolist())

zonas_nuevas = [
    "centros odontologicos Copacabana Antioquia",
    "centros odontologicos La Estrella Antioquia",
    "centros odontologicos Caldas Antioquia",
    "centros odontologicos Guayabal Medellin",
    "centros odontologicos Estadio Medellin",
    "centros odontologicos Floresta Medellin",
    "centros odontologicos San Javier Medellin",
    "centros odontologicos Popular Medellin",
    "centros odontologicos Santa Cruz Medellin"
]

nuevos_leads = []

def extraer_email(url):
    if not url or pd.isna(url):
        return ""
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=8)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', response.text)
        emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example'])]
        return emails[0] if emails else ""
    except:
        return ""

def extraer_whatsapp(web, telefono):
    if web and not pd.isna(web):
        wa = re.findall(r'wa\.me/(\d+)', str(web))
        if wa:
            return "+" + wa[0]
    if telefono and not pd.isna(telefono):
        numero = re.sub(r'\D', '', str(telefono))
        if numero.startswith('3') and len(numero) == 10:
            return "+57" + numero
        if numero.startswith('573') and len(numero) == 12:
            return "+" + numero
    return ""

for zona in zonas_nuevas:
    print(f"\nBuscando: {zona}")
    params = {"query": zona, "key": API_KEY, "language": "es"}
    
    while True:
        response = requests.get(url_search, params=params).json()
        
        for place in response.get("results", []):
            place_id = place.get("place_id", "")
            
            if place_id in ids_vistos:
                print(f"Duplicado: {place.get('name')}")
                continue
            ids_vistos.add(place_id)
            
            details = requests.get(url_details, params={
                "place_id": place_id,
                "fields": "formatted_phone_number,website",
                "key": API_KEY
            }).json()
            
            web = details.get("result", {}).get("website", "")
            telefono = details.get("result", {}).get("formatted_phone_number", "")
            email = extraer_email(web)
            whatsapp = extraer_whatsapp(web, telefono)
            
            nuevos_leads.append({
                "Nombre": place.get("name", ""),
                "Direccion": place.get("formatted_address", ""),
                "Telefono": telefono,
                "Web": web,
                "Rating": place.get("rating", ""),
                "Email": email,
                "Zona": zona,
                "place_id": place_id,
                "WhatsApp": whatsapp
            })
            print(f"OK: {place.get('name')}")
        
        next_page_token = response.get("next_page_token")
        if next_page_token:
            time.sleep(3)
            params = {"pagetoken": next_page_token, "key": API_KEY}
        else:
            break

df_nuevos = pd.DataFrame(nuevos_leads)
df_final = pd.concat([df_existente, df_nuevos], ignore_index=True)
df_final.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(f"\nNuevos leads agregados: {len(nuevos_leads)}")
print(f"Total base de datos: {len(df_final)}")
df_final

Buscando: centros odontologicos Copacabana Antioquia
OK: Consultorio Odontológico MCC ODONTOLOGY.
OK: Consultorio Odontológico MyDentale
OK: OralSalud Odontología Integral
OK: SonriDental
OK: Consultorio Odontológico Dra Natalia Zapata
OK: Consultorio Odontologico Lina Uribe
OK: D3Dental
Duplicado: Dental line
OK: Odontonorte
OK: Bocca Odontología Integral
OK: Centro odontológico siqueira campos
OK: Odontimax Odontologia
OK: Centro de Odontología Contemporánea

Buscando: centros odontologicos La Estrella Antioquia
OK: CLÍNICA DR. BLANC LA ESTRELLA
OK: o mas dental
OK: Dentart
OK: Dental Star Odontología
OK: Dontológica
OK: Solo Sonrisas - Odontología - Diseño Sonrisa- Estética facial
OK: Macridental
OK: centro dental bioser
Duplicado: Dra. Lisbed Giraldo Olarte, Odontólogo
OK: Consultorio Odontológico y psicologico Dra Natalia Tobon
OK: Consultorio Odontológico Adriana Aguirre
Duplicado: CREADENTISS, odontología integral
OK: Centro Odontológico Kr60

Buscando: centros odontologicos Caldas Antioquia
OK: Prevenga Odontología Particular - Caldas
OK: Esencial Odontología Especializada
Duplicado: Consultorio Robledo Odontología Integral
OK: SMILE Clinica Odontológica sede Caldas
OK: Consultorio Carolina Perez Rendon, Caldas -Ant
OK: Grupo Odontoavances
OK: Oscar Tavera Ortodoncia | Odontología Especializada
OK: Centro Radiologico Oral Odontox
OK: Centro radiológico odontox
OK: Diagnostic Oral Caldas
Duplicado: Centro Odontologico Robledo
OK: Consultorio Médico Del Sur - Dr. Santiago Arbeláez Monsalve
OK: Mundo Oral Caldas Especialistas en Odontologia
OK: Policlínico Sur S.A - Calidad de Vida

Buscando: centros odontologicos Guayabal Medellin
Duplicado: Dental Expertos
OK: Odontopraxis | Odontología Medellín | Odontológos
OK: Odontoplux
OK: centro odontologico campo amor
OK: Clinica Odontologica Dental Life
Duplicado: Oral Studio
Duplicado: centro odontologico la 65
Duplicado: Smile Natural Studio | Clínica & Spa Odontológico
Duplicado: ORAL CONCEPT INVISALIGN
OK: Centro Médico Odontológico Sima Salud Integral
Duplicado: Consultorio Odontológico Vida Oral
Duplicado: Royal Dental Care
Duplicado: Urgencias Odontológicas 24 horas las Vegas
Duplicado: Dora Álvarez
Duplicado: ORAL MAS ESPECIALISTAS
Duplicado: CR Dental Studio
Duplicado: Odontología 30a
OK: MEC Dental
Duplicado: Odontología el Poblado - Oral 10 - Diseños de Sonrisa en Medellín
OK: Dentilandia Odontología para Niños / Odontopediatria Medellin
Duplicado: Dental Center
Duplicado: DentiOral - Sede Belén
OK: Dra. Ángela Giraldo
OK: DentalMás. Tu clínica de sonrisas
OK: Paulina Zarrabe Odontologia Integral
OK: ORALMAAX
Duplicado: Consultorio Odontológico OC
Duplicado: Centro Vital, Odontología Integral
OK: Odontología Las Américas
OK: E.Smile Clinica de Odontología Integral
Duplicado: DentiSalud El Poblado - Clínicas Odontológicas
Duplicado: Oral Center Poblado
Duplicado: Odontocer, Centro de Estética y Rehabilitación Oral
OK: LET Dental Studio
OK: Centro Odontologico Servicio Integral
OK: S&R odontólogos especialistas
Duplicado: Odontólogos y Especialistas
OK: Enlace Dental
Duplicado: Dr Andres Alvarez Implantologo oral y Rehabiltacion
Duplicado: Focus Dental Center Odontología
Duplicado: Orthodontics Medellín
Duplicado: 360 Dental Group IPS | Clínica Odontológica Mayorca
OK: Marcela Ramírez Odontología
Duplicado: Clínica Odontológica de Antioquia - CLODAN sas.
Duplicado: San José Centro Odontológico
OK: Alejo Villegas Odontología
OK: Dental House
OK: Odontología de Paola Alvarez
Duplicado: Neodental Centro Odontológico
Duplicado: Urgencias Odontologicas del Sur
Duplicado: Lina Fernández Odontología - Diseño de sonrisa y Blanqueamiento dental en Medellín
OK: Ortodoncista Medellin Dr. Jaime Andres Agudelo
OK: Todoral Odontología Especializada
Duplicado: Dental Specialists Medellín
OK: Oral Láser
OK: Nova Smile
OK: Yasmin Arias Consultorio Odontológico
OK: Torre Médica Salud Vegas
Duplicado: Centro Odontológico White Dental
Duplicado: Dr. Andrés Fuertes odontología ética y responsable.

Buscando: centros odontologicos Estadio Medellin
Duplicado: Clínica Odontológica Oral Laser Estadio
OK: Tiago Odontologia
Duplicado: Dra Liliana Gutiérrez L.
Duplicado: Oral Center Distrito 65
Duplicado: Consultorio odontologico la 73
Duplicado: URGENCIAS ODONTOLOGICAS, MEDELLÍN
OK: Clinica Odontoser
Duplicado: Clínica Dental Home
Duplicado: Dento Grupo Odontológico
Duplicado: Dr. Mauricio Arias - Odontólogo Experto en Medellín English Dentist
Duplicado: Oral Elite Consultorio Odontológico atendido por el Dr Alejandro Ramírez
OK: Consultorio odontológico Johana Patiño Arias
Duplicado: Centro Radiológico Oral Centro de Medellin
Duplicado: Camila Paredes Odontología
Duplicado: Clínica Odontológica Oral Laser Centro
OK: BETTER SMILE odontología digital especializada
Duplicado: DentiSalud Floresta - Clínica odontológica
Duplicado: Royal Dental Care
OK: Odonto Super
OK: Oral Gold
OK: Odontología Total
Duplicado: Dental By
Duplicado: Ortoclin Sede Santa Lucia
Duplicado: Oral Studio
Duplicado: Dental Center
Duplicado: Odontologos en Medellin
OK: Clinic Complet
OK: Centro Radiológico RADO - Sede Obelisco
Duplicado: Oral Center Poblado
Duplicado: San José Centro Odontológico
OK: Unidad Robótica Dental - Odontología 3D Medellín
Duplicado: Bocas&Risas - Clínica Odontológica en Medellín
OK: OZONODENTALGROUP
Duplicado: Alternativas Odontológicas
OK: Centro Comercial Obelisco
OK: DIAMOND DENTAL
Duplicado: Ortoclin Sede Floresta
OK: Centro Profesional Conquistadores
Duplicado: Odontología Las Américas
OK: Odontologia Zaffiro dental group
OK: LAURA CORREA Odontología integral y estética
Duplicado: Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín
OK: Laboratorio Clínico AndiLab S.A.S
OK: Rent Dental Space alquiler de consultorios odontologicos Medellin
OK: Alejandro Arango A. InnovationDental
Duplicado: Clínica Dental Home
OK: Laboratorio Dental VID
Duplicado: Estacion Oral
OK: Coe
OK: CEODIN
OK: DRA. ELIANA P GIRON
Duplicado: Oral Láser
OK: Consultorios Odontológicos
Duplicado: DentiOral - Sede Belén
Duplicado: DentiSalud El Poblado - Clínicas Odontológicas
OK: Urgencias Odontológicas
Duplicado: Odonto Rio - Estudio Dental
OK: Coral Odontología Estética
OK: Ecodental
OK: Radiografiax odontologicax

Buscando: centros odontologicos Floresta Medellin
Duplicado: Ortoclin Sede Floresta
OK: Consultorio Odontologico La Floresta M&D Dental
OK: Dentiplan Floresta
Duplicado: DentiSalud Floresta - Clínica odontológica
Duplicado: Odonto Super
OK: Dt. Dental
OK: Sonría

Buscando: centros odontologicos San Javier Medellin
OK: Dental Sonrisas
OK: Odontologia San Javier
OK: Ortoclin Sede San javier
OK: Consultorio Odontológico Particular
OK: Centro odontológico OrtoPlus
OK: Dentali odontología - Sede San Javier
OK: ORTHO ESTETIKA . SANJAVIER

Buscando: centros odontologicos Popular Medellin
Duplicado: Centro odontológico KMO Smile Especialistas
Duplicado: Premium Dental Medellín
Duplicado: Dra. Maru Odontología y Estética Facial
Duplicado: Odontoespecialistas
Duplicado: Infinity Smile
Duplicado: ORAL CONCEPT INVISALIGN
Duplicado: Dra. Ana Zuluaga - Diseño de Sonrisa en Medellín
Duplicado: Dentioral - Sede Poblado
Duplicado: Smile Natural Studio | Clínica & Spa Odontológico
Duplicado: Sanadent Odontólogos - La Mejor Clínica Dental en Medellín
Duplicado: CR Dental Studio
Duplicado: Clínica Viena / Veneers Medellín
OK: Koodent
Duplicado: Dental Center
Duplicado: Clínica Dental Home
Duplicado: Jenny Villada Clínicas Odontológicas
Duplicado: Oral Studio
Duplicado: Naturaldent
Duplicado: Oral Elite Consultorio Odontológico atendido por el Dr Alejandro Ramírez
OK: CENTRO DENTAL POPULAR #2

Buscando: centros odontologicos Santa Cruz Medellin
OK: Dental Force Santa Cruz
OK: Unidad Hospitalaria Santa Cruz

Nuevos leads agregados: 105
Total base de datos: 517

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona,place_id,WhatsApp
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,NaN,centros odontologicos El Poblado Medellin,ChIJX2o-xYGCRo4Rn6L7wacsRJo,NaN
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin,ChIJgwmJfiYoRI4RvO8goH3oe7M,NaN
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,NaN,centros odontologicos El Poblado Medellin,ChIJc8AO2KUpRI4R5lZzeBklf3U,573146628875.0
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin,ChIJ42xK_4kpRI4RwY-W14dE_BU,573246027040.0
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin,ChIJN3fIPZ8pRI4RytlAMwH5Zuw,573011795872.0
...,...,...,...,...,...,...,...,...,...
512,ORTHO ESTETIKA . SANJAVIER,"Cl 42 #101-73, Medellín, San Javier, Medellín,...",,,3.8,,centros odontologicos San Javier Medellin,ChIJXeYnq9opRI4R_rGC_3MDNao,
513,Koodent,"Cra. 86B #47A-27, La América, Medellín, La Amé...",311 3081680,https://www.instagram.com/koodent/,4.9,,centros odontologicos Popular Medellin,ChIJ3VwBe2spRI4R4U3AYHckB3I,+573113081680
514,CENTRO DENTAL POPULAR #2,"Cl. 55 #56A-64, La Candelaria, Medellín, La Ca...",45128881,,,,centros odontologicos Popular Medellin,ChIJoYCxof0oRI4RMOb-PJCxTBM,
515,Dental Force Santa Cruz,"Cra. 43a #104-26, Villa Del Socorro, Medellín,...",314 6940090,,5,,centros odontologicos Santa Cruz Medellin,ChIJD3e3GKsvRI4RP60CDYO6lBw,+573146940090
516,Unidad Hospitalaria Santa Cruz,"Cra 51A #100-80, Santa Cruz, Medellín, Santa C...",311 5146800,http://www.metrosalud.gov.co/sedes/upss-santa-...,3.5,,centros odontologicos Santa Cruz Medellin,ChIJebSWSTIvRI4RQQ5eR6AK0HA,+573115146800

In [36]:
import pandas as pd

df = pd.read_excel("leads_odontologos_medellin_completo.xlsx")
print(df["Zona"].value_counts())

Zona
centros odontologicos Laureles Medellin        59
centros odontologicos Envigado                 58
centros odontologicos Itagui                   52
centros odontologicos El Poblado Medellin      51
centros odontologicos Bello                    46
centros odontologicos Centro Medellin          33
centros odontologicos Estadio Medellin         28
centros odontologicos Guayabal Medellin        27
centros odontologicos Sabaneta                 25
centros odontologicos Belen Medellin           22
centros odontologicos Castilla Medellin        19
centros odontologicos Manrique Medellin        18
centros odontologicos Copacabana Antioquia     12
centros odontologicos Caldas Antioquia         12
centros odontologicos La Estrella Antioquia    11
centros odontologicos Robledo Medellin         10
centros odontologicos Buenos Aires Medellin    10
centros odontologicos Aranjuez Medellin         9
centros odontologicos San Javier Medellin       7
centros odontologicos Floresta Medellin         4
centros odontologicos Popular Medellin          2
centros odontologicos Santa Cruz Medellin       2
Name: count, dtype: int64

In [38]:
import pandas as pd

df = pd.read_excel("leads_odontologos_medellin_completo.xlsx")

# Mapeo de zonas a comunas
comunas = {
    "centros odontologicos Laureles Medellin": "Comuna 11 - Laureles Estadio",
    "centros odontologicos Estadio Medellin": "Comuna 11 - Laureles Estadio",
    "centros odontologicos Floresta Medellin": "Comuna 11 - Laureles Estadio",
    "centros odontologicos El Poblado Medellin": "Comuna 14 - El Poblado",
    "centros odontologicos Centro Medellin": "Comuna 10 - La Candelaria",
    "centros odontologicos Belen Medellin": "Comuna 16 - Belen",
    "centros odontologicos Robledo Medellin": "Comuna 7 - Robledo",
    "centros odontologicos Castilla Medellin": "Comuna 5 - Castilla",
    "centros odontologicos Guayabal Medellin": "Comuna 15 - Guayabal",
    "centros odontologicos Buenos Aires Medellin": "Comuna 9 - Buenos Aires",
    "centros odontologicos Manrique Medellin": "Comuna 3 - Manrique",
    "centros odontologicos Aranjuez Medellin": "Comuna 4 - Aranjuez",
    "centros odontologicos San Javier Medellin": "Comuna 13 - San Javier",
    "centros odontologicos Popular Medellin": "Comuna 1 - Popular",
    "centros odontologicos Santa Cruz Medellin": "Comuna 2 - Santa Cruz",
    "centros odontologicos Envigado": "Municipio - Envigado",
    "centros odontologicos Itagui": "Municipio - Itagui",
    "centros odontologicos Bello": "Municipio - Bello",
    "centros odontologicos Sabaneta": "Municipio - Sabaneta",
    "centros odontologicos Copacabana Antioquia": "Municipio - Copacabana",
    "centros odontologicos La Estrella Antioquia": "Municipio - La Estrella",
    "centros odontologicos Caldas Antioquia": "Municipio - Caldas"
}

df["Comuna"] = df["Zona"].map(comunas)

df.to_excel("leads_odontologos_medellin_completo.xlsx", index=False)
print(df["Comuna"].value_counts())
df

Comuna
Comuna 11 - Laureles Estadio    91
Municipio - Envigado            58
Municipio - Itagui              52
Comuna 14 - El Poblado          51
Municipio - Bello               46
Comuna 10 - La Candelaria       33
Comuna 15 - Guayabal            27
Municipio - Sabaneta            25
Comuna 16 - Belen               22
Comuna 5 - Castilla             19
Comuna 3 - Manrique             18
Municipio - Copacabana          12
Municipio - Caldas              12
Municipio - La Estrella         11
Comuna 7 - Robledo              10
Comuna 9 - Buenos Aires         10
Comuna 4 - Aranjuez              9
Comuna 13 - San Javier           7
Comuna 1 - Popular               2
Comuna 2 - Santa Cruz            2
Name: count, dtype: int64

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona,place_id,WhatsApp,Comuna
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,NaN,centros odontologicos El Poblado Medellin,ChIJX2o-xYGCRo4Rn6L7wacsRJo,NaN,Comuna 14 - El Poblado
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin,ChIJgwmJfiYoRI4RvO8goH3oe7M,NaN,Comuna 14 - El Poblado
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,NaN,centros odontologicos El Poblado Medellin,ChIJc8AO2KUpRI4R5lZzeBklf3U,5.731466e+11,Comuna 14 - El Poblado
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin,ChIJ42xK_4kpRI4RwY-W14dE_BU,5.732460e+11,Comuna 14 - El Poblado
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin,ChIJN3fIPZ8pRI4RytlAMwH5Zuw,5.730118e+11,Comuna 14 - El Poblado
...,...,...,...,...,...,...,...,...,...,...
512,ORTHO ESTETIKA . SANJAVIER,"Cl 42 #101-73, Medellín, San Javier, Medellín,...",NaN,NaN,3.8,NaN,centros odontologicos San Javier Medellin,ChIJXeYnq9opRI4R_rGC_3MDNao,NaN,Comuna 13 - San Javier
513,Koodent,"Cra. 86B #47A-27, La América, Medellín, La Amé...",311 3081680,https://www.instagram.com/koodent/,4.9,NaN,centros odontologicos Popular Medellin,ChIJ3VwBe2spRI4R4U3AYHckB3I,5.731131e+11,Comuna 1 - Popular
514,CENTRO DENTAL POPULAR #2,"Cl. 55 #56A-64, La Candelaria, Medellín, La Ca...",45128881,NaN,NaN,NaN,centros odontologicos Popular Medellin,ChIJoYCxof0oRI4RMOb-PJCxTBM,NaN,Comuna 1 - Popular
515,Dental Force Santa Cruz,"Cra. 43a #104-26, Villa Del Socorro, Medellín,...",314 6940090,NaN,5.0,NaN,centros odontologicos Santa Cruz Medellin,ChIJD3e3GKsvRI4RP60CDYO6lBw,5.731469e+11,Comuna 2 - Santa Cruz
516,Unidad Hospitalaria Santa Cruz,"Cra 51A #100-80, Santa Cruz, Medellín, Santa C...",311 5146800,http://www.metrosalud.gov.co/sedes/upss-santa-...,3.5,NaN,centros odontologicos Santa Cruz Medellin,ChIJebSWSTIvRI4RQQ5eR6AK0HA,5.731151e+11,Comuna 2 - Santa Cruz

In [39]:
import pandas as pd

df = pd.read_excel("leads_odontologos_medellin_completo.xlsx")
df["Categoria"] = "Salud"
df["Subcategoria"] = "Odontologia"
df.to_excel("leads_medellin_completo.xlsx", index=False)
print(f"Listo: {len(df)} registros actualizados")
print(df.columns.tolist())

Listo: 517 registros actualizados
['Nombre', 'Direccion', 'Telefono', 'Web', 'Rating', 'Email', 'Zona', 'place_id', 'WhatsApp', 'Comuna', 'Categoria', 'Subcategoria']

In [40]:
import requests
import pandas as pd
import time
import re

API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"
url_search = "https://maps.googleapis.com/maps/api/place/textsearch/json"
url_details = "https://maps.googleapis.com/maps/api/place/details/json"

# Cargar base existente
df_existente = pd.read_excel("leads_medellin_completo.xlsx")
ids_vistos = set(df_existente["place_id"].dropna().tolist())

zonas = [
    "clinicas estetica El Poblado Medellin",
    "clinicas estetica Laureles Medellin",
    "clinicas estetica Envigado",
    "clinicas estetica Bello",
    "clinicas estetica Itagui",
    "clinicas estetica Centro Medellin",
    "clinicas estetica Sabaneta",
    "clinicas estetica Belen Medellin",
    "clinicas estetica Robledo Medellin",
    "clinicas estetica Castilla Medellin",
    "clinicas estetica Buenos Aires Medellin",
    "clinicas estetica Manrique Medellin",
    "clinicas estetica Aranjuez Medellin",
    "clinicas estetica Copacabana Antioquia",
    "clinicas estetica La Estrella Antioquia",
    "clinicas estetica Caldas Antioquia",
    "clinicas estetica Guayabal Medellin",
    "clinicas estetica Estadio Medellin",
    "clinicas estetica Floresta Medellin",
    "clinicas estetica San Javier Medellin",
    "clinicas estetica Popular Medellin",
    "clinicas estetica Santa Cruz Medellin"
]

comunas = {
    "clinicas estetica Laureles Medellin": "Comuna 11 - Laureles Estadio",
    "clinicas estetica Estadio Medellin": "Comuna 11 - Laureles Estadio",
    "clinicas estetica Floresta Medellin": "Comuna 11 - Laureles Estadio",
    "clinicas estetica El Poblado Medellin": "Comuna 14 - El Poblado",
    "clinicas estetica Centro Medellin": "Comuna 10 - La Candelaria",
    "clinicas estetica Belen Medellin": "Comuna 16 - Belen",
    "clinicas estetica Robledo Medellin": "Comuna 7 - Robledo",
    "clinicas estetica Castilla Medellin": "Comuna 5 - Castilla",
    "clinicas estetica Guayabal Medellin": "Comuna 15 - Guayabal",
    "clinicas estetica Buenos Aires Medellin": "Comuna 9 - Buenos Aires",
    "clinicas estetica Manrique Medellin": "Comuna 3 - Manrique",
    "clinicas estetica Aranjuez Medellin": "Comuna 4 - Aranjuez",
    "clinicas estetica San Javier Medellin": "Comuna 13 - San Javier",
    "clinicas estetica Popular Medellin": "Comuna 1 - Popular",
    "clinicas estetica Santa Cruz Medellin": "Comuna 2 - Santa Cruz",
    "clinicas estetica Envigado": "Municipio - Envigado",
    "clinicas estetica Itagui": "Municipio - Itagui",
    "clinicas estetica Bello": "Municipio - Bello",
    "clinicas estetica Sabaneta": "Municipio - Sabaneta",
    "clinicas estetica Copacabana Antioquia": "Municipio - Copacabana",
    "clinicas estetica La Estrella Antioquia": "Municipio - La Estrella",
    "clinicas estetica Caldas Antioquia": "Municipio - Caldas"
}

nuevos_leads = []

def extraer_email(url):
    if not url or pd.isna(url):
        return ""
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=8)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', response.text)
        emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example'])]
        return emails[0] if emails else ""
    except:
        return ""

def extraer_whatsapp(web, telefono):
    if web and not pd.isna(web):
        wa = re.findall(r'wa\.me/(\d+)', str(web))
        if wa:
            return "+" + wa[0]
    if telefono and not pd.isna(telefono):
        numero = re.sub(r'\D', '', str(telefono))
        if numero.startswith('3') and len(numero) == 10:
            return "+57" + numero
        if numero.startswith('573') and len(numero) == 12:
            return "+" + numero
    return ""

for zona in zonas:
    print(f"\nBuscando: {zona}")
    params = {"query": zona, "key": API_KEY, "language": "es"}
    
    while True:
        response = requests.get(url_search, params=params).json()
        
        for place in response.get("results", []):
            place_id = place.get("place_id", "")
            if place_id in ids_vistos:
                print(f"Duplicado: {place.get('name')}")
                continue
            ids_vistos.add(place_id)
            
            details = requests.get(url_details, params={
                "place_id": place_id,
                "fields": "formatted_phone_number,website",
                "key": API_KEY
            }).json()
            
            web = details.get("result", {}).get("website", "")
            telefono = details.get("result", {}).get("formatted_phone_number", "")
            email = extraer_email(web)
            whatsapp = extraer_whatsapp(web, telefono)
            
            nuevos_leads.append({
                "Nombre": place.get("name", ""),
                "Direccion": place.get("formatted_address", ""),
                "Telefono": telefono,
                "Web": web,
                "Rating": place.get("rating", ""),
                "Email": email,
                "Zona": zona,
                "place_id": place_id,
                "WhatsApp": whatsapp,
                "Comuna": comunas.get(zona, ""),
                "Categoria": "Estetica",
                "Subcategoria": "Clinica Estetica"
            })
            print(f"OK: {place.get('name')}")
        
        next_page_token = response.get("next_page_token")
        if next_page_token:
            time.sleep(3)
            params = {"pagetoken": next_page_token, "key": API_KEY}
        else:
            break

df_nuevos = pd.DataFrame(nuevos_leads)
df_final = pd.concat([df_existente, df_nuevos], ignore_index=True)
df_final.to_excel("leads_medellin_completo.xlsx", index=False)
print(f"\nNuevos leads estetica: {len(nuevos_leads)}")
print(f"Total base de datos: {len(df_final)}")
df_final

Buscando: clinicas estetica El Poblado Medellin
OK: Wellnes Spa by Clínica Antienvejecimiento, spa Medellín, spa parejas, spa poblado, clínica estética, revitalización facial
OK: Dra.Pastrana Medicina Estética Medellín
OK: Massai Clínica - Clínica Estética en Medellín
OK: Clínica Especialistas del Poblado
OK: EVOLVE Clínica Estética
OK: CentroSthetic
OK: Botox and Fillers Medellin Dra Catalina Henao Medicina antienvejecimiento
OK: Brassia Estética Poblado
OK: Bonanova Medicina Estética y Bienestar
OK: Clínica Quantum
OK: Centro Médico Femo Estética - Medellín Poblado
OK: Dra Monica Pineda | MP Medical Center
OK: Naturalness | Medicina Estética
OK: Spa Médica - Dr. Juan Mario Escobar
OK: Integral Esthetic Botox / Facial / Fillers / Microagujas
OK: Siempreviva Medicina Estética Medellín Poblado
OK: Cirugía Plástica Medellin /Colombia Plastic Esthetic International
OK: Dr. Escorcia
OK: Alviva Clínica Estética
OK: Clínica Mery Álvarez - Sede Poblado
OK: Cirugia Plastica Medellin
OK: Medicina y Antienvejecimiento Medellín - Dra. Adriana Múnera
OK: Dra. Yulieth Figueroa
OK: Grupo Estético CB
OK: Dra. Angeles Esmeral
OK: Clinica Be Dharma
OK: Dra Amy Barreto - Blefaroplastia Abdominoplastia Liposucción Mastopexia Lifting facial Labioplastia Lipoma Cirugía Varices
OK: byDraLinaCardona
OK: Rada Cassab Medicina Estética Medellín
OK: Cirugía Estética Avanzada - Cirugia Plastica
OK: Dra. Laura Margarita Arango - Dermatóloga estética y clínica
OK: Anay Clínica Estética
OK: Equal Más Vida. Más Belleza
OK: Clínica LIV
Duplicado: Dra. Maru Odontología y Estética Facial
OK: Satori IPS Medicina Estética
OK: Dr. Yesid Cardenas
OK: Dra Laura Astoquiza| Estética Médica
OK: Dr. Milton Rincón Carranza
OK: ACICME
OK: Dra. Miralba Montoya | Medicina Estética
OK: Le Spa Noir
OK: Cirugia Plastica Facial Dr Edgar Felipe Diaz - Rinoplastia
OK: Glam Beauty Bar
OK: Glow Up Center
OK: Clínica Medellín Sede El Poblado
OK: Centro de Estética & Spa Yaneth Sibaja
OK: Financiacion Cirugia Plastica - Plan Médico Y Quirúrgico
OK: Zaharum Medical Spa Poblado
OK: Chicago Beauty
OK: Medicina Estética Medellin
OK: Dashka Salon
OK: Dr Alvaro Correa Jaramillo. Experto en Rinoplastia y Rejuvenecimiento Facial
OK: Spa Estética Facial
OK: Massage spa in medellín /Vita Therapy Medellín
OK: MAHAI.WELLNESS Massage Therapy & Spa
OK: Santa María Estética
OK: Dr.José Alfredo Burgos
OK: IQ InterQuirófanos - Torre Médical
OK: Eclat Provenza SPA

Buscando: clinicas estetica Laureles Medellin
OK: Brassia Estética Laureles
OK: Dra. Evelin Ortiz - Medicina estética y antienvejecimiento
OK: Clínica Laser
OK: Skin Centro Estético
OK: CyE Centro de estética - spa
OK: BELLEZA LAURELES
OK: Dra. Ángela Arroyo • Medicina Estética en Medellín - Bótox - Sculptra - Ácido hialurónico
OK: Centro de Estética Gloria López
OK: Derma Skin Care - Aesthetic Clinic Laureles
OK: Dra. Alejandra Restrepo - Medicina Estética
OK: Monica Arboleda Centro Estético
OK: CLINIQ DERMOESTÉTICA Y LÁSER S.A
OK: Senzzes Sede Laureles
Duplicado: Dra Monica Pineda | MP Medical Center
OK: Centro de estética HSN
OK: Clinica Mery Álvarez - Laureles
OK: Silumed Medicina Estética
OK: IM CLÍNIC
OK: Saestheticspamedellin
OK: Depilarte Laureles
OK: Aqualuna Spa Laureles- Días de spa Medellín
OK: DermaFeeling Spa
OK: 5.0 🌟 Depilación laser hair removal Medellín Dulce Vanidad Centro Estético
OK: Santorinni
OK: Centro Estética Manzana Verde
OK: Happy Nails & Spa Sede Laureles - Medellín
OK: BELLEZA Y ARMONIA
OK: Dermatológica Laureles
OK: Rizos Felices
OK: Donna Reyther Esthetic Center
Duplicado: Alta Estetica Dental Laureles
OK: Black & White Medicina Estética Integral
OK: Estética y Belleza IPS
OK: Dr. Andrés Duque, medicina estética
OK: Spa de uñas | Lilah Nails | Manicure y pedicure en laureles
OK: NUEVA PIEL SPA
OK: Aleia Centro de Bienestar
OK: BODYBRITE LAURELES
OK: SAVI CENTRO DE ESTÉTICA INTEGRAL
OK: Maria camila alvarez medicina estética integral
OK: Centro de estética y bienestar Candamil
OK: Ō by Dr. Bretón Franco Medicina Estética - Dr. Juan Guillermo Bretón Franco
OK: HIDROLIPOCLASIA MEDELLIN
OK: Alanjara Centro de Belleza y Estética
OK: Freya Centro Estético
OK: Centro Médico Femo Estética
OK: Centro de estética Angelus
OK: Selem centro estético
OK: Bukuri Centro Médico y estético
OK: Luisa Correa Estética
OK: Centro de Belleza Juliana Ruiz
OK: Dermatóloga Luisa Ríos - Dermatología Clínica y Estética - Dermatólogos Medellín - Consulta Dermatológica Niños y Adultos
OK: Liso Saludable Laureles
OK: Uparela's Studio de Cejas
OK: Linda Piel Laser Center
OK: Odontologia Isabella Jaramillo estética dental y funcional
OK: DRA YESICA GOMEZ
OK: Bonitas spa de belleza
OK: Benessere Medicina Estetica
Duplicado: OdontoestéticaDH

Buscando: clinicas estetica Envigado
OK: Estetica Maria Camila Envigado
OK: Centro Estético Wendy de la Hoz
OK: Clínica Nova
OK: NURA Clínica de Belleza
OK: Equal Más Vida. Más Belleza
OK: Ethernia
OK: Jlassbelleza
OK: Doctor Samuel Restrepo|Imagen Perfecta|Medicina Antienvejecimiento|Limpieza Facial Profunda|Botox|Rejuvenecimiento Facial|
OK: Vida cosmetologia y estética
Duplicado: Massai Clínica - Clínica Estética en Medellín
OK: Nudela Clinic | Centro De Estética
OK: Centro de Belleza y Estética Bellísimas
OK: Miss Divina Center
OK: Cliniestetica
OK: INNOSTETIC S.A.S
OK: Dra. Ana María Restrepo Hernández - Medicina General
OK: Siempre Bella Envigado
OK: NC Estilista
OK: Ungla Centro de Belleza
OK: Tu Belleza Armonica
OK: Skincare Protection & Renovation
OK: Ela Centro Estético
OK: Drt S.A.S.
OK: Bluma Studio/Cejas-Balayage-Alisados Envigado
OK: My Medical Clinic
OK: The Lush Lounge Beauty Spa
OK: Bela Centro De Estética
OK: Dermatológica C.C. Viva Envigado
OK: CHALO Estilista Profesional
OK: LQ Essential Spa
OK: Castaño Láser y Estética
OK: CLINICA ACTIVECARE SAS
OK: Eternal Beauty Centro de Cosmetología Y Estética Integral
OK: QUEEN BEAUTY C.C. CITY PLAZA envigado - Extensiones de pestañas - Micropigmentación - Spa de Uñas - Cuidado Facial y Corporal
OK: Clinica Isis IPS
OK: Atenaz woman salón de belleza - envigado
OK: Centro Estético Agua Viva
Duplicado: CentroSthetic
OK: Línea Estética CC. Viva Envigado Local 222A
OK: Consultorio de Medicina Estética, Antienvejecimiento Dr Jorge Porras
OK: Dra Jessica Giraldo Ospina
OK: Lorena Orjuela Estética Integral
OK: Spa Armonía y Belleza con Estilo
OK: Palacio de la Keratina envigado
OK: Nathivas spa
OK: Otus Spa
OK: Pao Rojas Studio
OK: Cristina Sierra VIP - Envigado
OK: Solo Cejas Envigado Parque
OK: Sala Belleza Envigado - Catalina Uribe Profesionales Belleza
OK: Grupo Estético Elixir
OK: Dra. Paulina Tirado
OK: Depilarte Viva Envigado
OK: Miss Cejas Spa Envigado
OK: Centro Estético Leidy Londoño
OK: Estudio de Belleza Neyda Camacho
OK: Centro de Estética Yerbabuena
OK: Soler Envigado - Centro de Bronceo y Rejuvenecimiento High Tech
OK: Odontología Estética Especializada Envigado Victor A. Sossa Pérez
OK: Uñas & glamour

Buscando: clinicas estetica Bello
OK: Centro Salud & Belleza Bello
OK: Centro Estetico y Cosmetologico Del Norte
OK: Bel Medicina Estética
OK: Bello spa
OK: KA Esthetic Salud y Belleza
OK: ICONO SPA ★
OK: Estética Sara pino
OK: Enjoy estética- spa
OK: ALISADOS EN BELLO | RESTAURACIÓN CAPILAR EN BELLO | TINTE DE CABELLO EN BELLO
OK: Victoria Beauty
OK: Mundo Pestañas Spa
OK: Centro Estetico Tendencias y Estilo
OK: Aquiub Casa de Pestañas Bello
OK: Belle Peau | Centro de Medicina Estética en Bello
OK: Depilarte Bello
OK: Be Live Centro de Estética
OK: Eliana Arévalo Spa
OK: Centro De Belleza Integral Angeles Bellos
OK: Acuarela Belleza y Salud - Parque Fabricato
OK: Natural Fashion Bello - Expertos en Micropigmentación
OK: PLATINUM Centro de Belleza
OK: BOGA Centro Integral De Belleza
OK: KG Nails and Beauty
Duplicado: Dentotal
OK: vanessa rios-cosmetologa -bello micropigmentación
OK: DiansClinic
OK: Di Bell Nails Spa En Bello
OK: Corpobello Medical Spa
OK: Spa Maria Bonita
OK: Super Mechas
OK: Bloom centro estético
OK: Colegiatura Antioqueña de Belleza
OK: Lovelly Spa - Estetica Integral
OK: MOKA SPA
Duplicado: Dra. Astrix Vivas | Odontología general y estética
Duplicado: Smile Me
OK: Liso Saludable Bello
OK: ASIA V.I.P UÑAS Y CABELLO
OK: Benditas Spa
OK: VISAGO BELLEZA Y SALUD
OK: Bello Beauty Bar
OK: Luisa Sierra Estética Integral
OK: Nilly Belleza y Bienestar
OK: Isabel Vélez Estética
OK: Ataraxia Spa de Uñas y Cejas
OK: Angel skin estetica
OK: Dahia Keratin - Sede Bello
OK: Cuerpo Ideal Estética Sede Bello
OK: Yesica Moreno Centro de alisados Bello
OK: Spa de uñas en Bello Angy Ciro Nails
OK: Depilarte Fabricato
OK: Le Petit Salón
OK: Spa De Uñas En Bello Santísima
OK: Lym centro de belleza
OK: Línea Estética - CC. Puerta del Norte Segunda Etapa Local 1021
OK: Vanessa Pulgarin Nails
OK: GlowLash Spa Cejas Y Pestañas .
OK: Magical SPA
OK: Milagros Spa
OK: Centro De Belleza Jenny

Buscando: clinicas estetica Itagui
OK: Aval Spa & Esthetic
OK: Estética Facial By Alejandra Arias
OK: Buon Corpo Estética
OK: Centro estético Laura Melisa
OK: ELITE CENTRO ESTÉTICO
OK: YM Beauty Studio
OK: Alquimia spa itagui
OK: Magic Beauty Spa
OK: Only Her Studio
OK: Medicina Estética Dr Javier Velez
OK: Báltica estética micropigmentación
OK: COQUETAS SPA ITAGUI
OK: Trilogía Spa
OK: Los Reyes de la Keratina
OK: monaco nails spa
OK: Experiencia Esvera
OK: Acqua Color Spa
OK: Cómo tú spa
OK: Real Casa de Alisados y Depilación Itagüí
Duplicado: CS&CS Salud Oral y Piel
OK: Sofia Naranjo Nails
OK: Estudio de Belleza - Kathe Rivera
OK: Lashesbykateb
OK: Centro Estético Leidy Barrera
OK: Luna spa
OK: HADASSAH cejas & pestañas
OK: Secret spa de uñas
OK: Implestetica
OK: Natalia Giraldo Salón Sede Itagüi
OK: Centro de Belleza Color Tech
OK: Estética Sandra Giraldo
OK: Esteticas janeth sede itagui
OK: Amarantha Beauty SPA
OK: Luzete Salon
OK: Bendito Naturals
OK: KAIROS PIERCING
OK: Tropical Nails Spa / Spa de uñas
OK: Profesional Cejas
OK: Figura y Sonrisas
OK: Pigment Pro
OK: Rómez Estética Integral
Duplicado: Centro Comercial y empresarial Itagüí Plaza
OK: Plaza Arrayanes
OK: Estética integral MS
OK: Yasmin Gaviria Especialista en Micropigmentación
OK: Meraki Sala de Belleza, spa de uñas y Barbería
OK: Melissa Alvarez Especialista en cejas y pestañas
OK: Spa Nails marianne
Duplicado: estilo Oral
OK: Tarot spa
OK: Arisha spa
OK: Andreina nails spa
OK: Rebecca nails spa
OK: Mantras Estetica
OK: Serena estudio de belleza
OK: MP-SPA
OK: PIES PERFECTOS CUIDADO ESPECIALIZADO
OK: Centro estético FB
OK: Solo Cejas - Barrio la independencia
OK: Exóticas Spa

Buscando: clinicas estetica Centro Medellin
Duplicado: Dra.Pastrana Medicina Estética Medellín
Duplicado: Massai Clínica - Clínica Estética en Medellín
Duplicado: Dra Monica Pineda | MP Medical Center
Duplicado: Wellnes Spa by Clínica Antienvejecimiento, spa Medellín, spa parejas, spa poblado, clínica estética, revitalización facial
Duplicado: CentroSthetic
Duplicado: Bonanova Medicina Estética y Bienestar
Duplicado: EVOLVE Clínica Estética
Duplicado: Dra. Evelin Ortiz - Medicina estética y antienvejecimiento
OK: Clínica de Estética - Centro de Belleza - Céu Te Cuida CC Molinos
OK: Dra. Stephania Pastrana - Medicina Estética
Duplicado: Cirugía Plástica Medellin /Colombia Plastic Esthetic International
Duplicado: Medicina y Antienvejecimiento Medellín - Dra. Adriana Múnera
OK: PRANA Clinic
Duplicado: Clínica Laser
Duplicado: Clinica Be Dharma
OK: Dra. Adriana Diaz - Estética Medica
Duplicado: Dra. Ángela Arroyo • Medicina Estética en Medellín - Bótox - Sculptra - Ácido hialurónico
Duplicado: Clínica Mery Álvarez - Sede Poblado
OK: Botox Medellín | Masajes reductores Medellín | Acido hialuronico genesis
OK: Clínica Mery Álvarez - Sede Centro
Duplicado: Clínica Quantum
Duplicado: Cirugía Estética Avanzada - Cirugia Plastica
Duplicado: Grupo Estético CB
Duplicado: Naturalness | Medicina Estética
Duplicado: Alviva Clínica Estética
Duplicado: Clínica Especialistas del Poblado
Duplicado: Rada Cassab Medicina Estética Medellín
OK: GEA Lipo Sin Cirugía Medellín
OK: Almaluna Centro Estético
Duplicado: Anay Clínica Estética
Duplicado: Equal Más Vida. Más Belleza
OK: Nativa Medicina Estética
Duplicado: Centro Médico Femo Estética - Medellín Poblado
Duplicado: byDraLinaCardona
Duplicado: Dr. Yesid Cardenas
Duplicado: Cirugia Plastica Medellin
Duplicado: Ō by Dr. Bretón Franco Medicina Estética - Dr. Juan Guillermo Bretón Franco
OK: Centro de Estética Spa Bolivia
Duplicado: Centro de Estética Gloria López
Duplicado: Satori IPS Medicina Estética
Duplicado: CLINIQ DERMOESTÉTICA Y LÁSER S.A
Duplicado: Centro de estética HSN
OK: ORU MEDICINA ESTETICA
OK: Odamed Centro de Estética y Salud
OK: María Eunice Betancourt - Medicina Estética
OK: Béleco Medicina Estética
Duplicado: Donna Reyther Esthetic Center
Duplicado: Derma Skin Care - Aesthetic Clinic Laureles
OK: Clinica Somos
Duplicado: ACICME
Duplicado: Clínica Nova
OK: Saudé Genuina | Medicina Funcional y Estética en Medellin
Duplicado: Black & White Medicina Estética Integral
Duplicado: Siempreviva Medicina Estética Medellín Poblado
OK: Clínica Bella Vie | Cirugía Plástica y Estética en Medellín
Duplicado: Bel Medicina Estética
OK: Centro De Estética | Céu Te Cuida | C.C. El Tesoro
OK: Clinica de cejas
OK: Dra. Patricia Uribe Pino. Oftalmóloga, Medellín. Colombia. Blefaroplastia・Cirugía Plástica y Estética Ocular.
OK: Savia

Buscando: clinicas estetica Sabaneta
OK: ESTETIK MARIA E
OK: Anama Clinic | Medicina Estética
OK: Medicina estética Karin
OK: Borage Concept Studio
OK: Sofia Muñoz Esthetic Center & Spa
OK: Cerarte Spa
OK: Creative Colors Salón
OK: casa canela spa
OK: Angy SPA
OK: Spa Alma White Sabaneta
OK: Centro de Estética y Belleza Bella Mia S.A.S.
OK: Paraíso Spa
OK: Almas Centro Estético
OK: Serenity Spa
OK: Aquiub Casa de Pestañas Sabaneta
OK: Athena Estudio de Belleza
OK: ConforPiel
OK: Centro Comercial Mayorca
OK: Amaspa
OK: Cejas y estética by Andrea Ramirez
OK: Valentina Echavarría Centro de belleza
OK: MG Pestañas - Sabaneta
OK: Limaica Studio-Depilacion con láser/cera.
Duplicado: Odontics Sabaneta
OK: Centro De Estética | Céu Te Cuida | C.C. Mayorca
OK: ISANIA beauty house
OK: J&T Centro de Acondicionamiento Estético
OK: Dra. Ximena Melo
OK: Glow Beauty Bar
OK: Mirella Acosta Spa and Stetic
OK: BM Spa de Uñas y Estética
OK: Toques de Belleza
OK: Matiz Salud y Belleza
OK: Lola Nails Spa
OK: centro estetico Luxury Beauty
OK: Vive Salon Beauty
OK: Centro De Estetica Lulu
OK: CH BEAUTY SALON SABANETA
OK: Solo Cejas - Sabaneta parque
OK: Centro De Belleza Amoret
OK: Sandra Olarte SPA
OK: Depilarte Sabaneta
OK: Vital Masoterapia
OK: Sky Beauty Spa Colombia
OK: Mariana Álvarez Beauty
OK: Pielez centro estético
OK: CENTRO DE ESTETICA ZACHA
OK: Spa Look violetts
OK: ODONTOLOGÍA AURA MARÍA
OK: ESSENS HAIR SALON & BARBERSHOP
Duplicado: Dra. Lisbed Giraldo Olarte, Odontólogo
OK: Dra. Paula Ànama
OK: Embell Studio -Sabaneta
Duplicado: Dr DNY Odontología Sabaneta
Duplicado: Clínica Total Harmony - Dr. Edison Giraldo
OK: Acuarela Belleza y Salud - Aves María
OK: Bloomy spa
OK: Lienzo SPA Uñas y Belleza – Sabaneta, Antioquia
OK: Elite Beauty spa
OK: Valeria Restrepo Z centro de estética

Buscando: clinicas estetica Belen Medellin
Duplicado: Clínica Bella Vie | Cirugía Plástica y Estética en Medellín
Duplicado: Clínica de Estética - Centro de Belleza - Céu Te Cuida CC Molinos
Duplicado: Massai Clínica - Clínica Estética en Medellín
OK: Malibú Centro Estético
Duplicado: Botox and Fillers Medellin Dra Catalina Henao Medicina antienvejecimiento
OK: Figurbell spa Reduce medidas de abdomen sin cirugias
OK: Belle Aesthetic Medical Center
Duplicado: Clinica Be Dharma
Duplicado: ProSmile Medellín - Expertos en Salud Bucal y Estética Dental
OK: Belén Estética
OK: Be Beauty by Valentina.
Duplicado: CentroSthetic
OK: Olgys Cejas
OK: Centro Estético Integral Rosales
Duplicado: Bel Medicina Estética
OK: clinica del cabello
Duplicado: SONRIESTHETIC ODONTOLOGÍA
Duplicado: CLINIQ DERMOESTÉTICA Y LÁSER S.A
OK: CELESTIAL TIENDA DE BELLEZA
Duplicado: Ortho Estetika
OK: Sublime sala de belleza
OK: lashesbytatigiraldo
OK: Escuela Belleza Artes y Oficios
OK: Marosa Nails Spa
OK: Instituto Nacional de Cosmetología y Estética Atenea
Duplicado: Clinica Somos
OK: The Heaven

Buscando: clinicas estetica Robledo Medellin
Duplicado: Dra.Pastrana Medicina Estética Medellín
OK: Spa Luna M
OK: Zahara Estética y Spa
Duplicado: Bonanova Medicina Estética y Bienestar
Duplicado: Massai Clínica - Clínica Estética en Medellín
OK: Calma centro de bienestar y estética integral
OK: Spa Divinas Nails
Duplicado: Skin Centro Estético
Duplicado: Centro de Estética Gloria López
Duplicado: Monica Arboleda Centro Estético
Duplicado: Dra Monica Pineda | MP Medical Center
Duplicado: Medicina y Antienvejecimiento Medellín - Dra. Adriana Múnera
Duplicado: Clinica Be Dharma
Duplicado: Almaluna Centro Estético
Duplicado: Clínica Quantum
Duplicado: IM CLÍNIC
Duplicado: CentroSthetic
OK: FASHION NAILS MED
Duplicado: Derma Skin Care - Aesthetic Clinic Laureles
Duplicado: Dra Laura Astoquiza| Estética Médica
OK: Vital Stetic IPS I Plasma Rico en Plaquetas I Depilación Láser I Cuidado facial y corporal I Suero Terapia
OK: Centro Estetico en Medellin - Unica Centro Estetico
OK: CENTRO ESTÉTICO D'ANGEL- Local 231
Duplicado: Ethernia
OK: Eterna Studio Robledo
OK: Concept Nails
OK: Solo Cejas - Robledo
OK: Encantadas cejas & pestañas
OK: Amatsu Spa - Masajes y Spa en Medellín
OK: Dulce Figura Spa - Masajes Reductores & Relajantes Medellín
Duplicado: Clínica Especialistas del Poblado
OK: Beauty Variedades
OK: Dr. Andrés Álvarez
OK: Viva Spa
OK: Mas Bella
OK: Maryo beauty
Duplicado: Instituto Nacional de Cosmetología y Estética Atenea
OK: Pestañas Sensación
OK: Éxito Robledo
OK: Sala de Belleza Unisex
OK: Parque Robledo
OK: Emunah Belleza Sobrenatural
OK: Samy nails manicurista
OK: Robledo bello horizonte
OK: Mercy Nails
OK: Angela Nails spa
Duplicado: Dra Jessica Giraldo Ospina
OK: Consultorio Odontologico Dr. Oscar Velásquez
OK: Centro Integral Salud y Belleza
OK: Angie

Buscando: clinicas estetica Castilla Medellin
OK: Centro Spa Castilla- Estetica Adri's
OK: Adahlia Spa
OK: Nice centro de belleza
OK: BIP PROFESIONAL - Artistas en Belleza
OK: Paulinails Sede Castilla
OK: Mimosas Spa
OK: MORETTA CENTRO ESTÉTICO
OK: Daniela Henao
OK: Divinas Medellin
OK: Sala de Belleza Doral
OK: Dlaser Medellin
OK: Divas Spa
OK: Salón Dahian's
OK: Bellísimas beuty spa
OK: LA CASITA D' LAS UÑAS
OK: MADRID SPA CEJAS Y PESTAÑAS
OK: Irinna spa
OK: Solo Cejas - Castilla
OK: Sara Nails
OK: Sueños Nails Spa
OK: Pestañas pelo a pelo y Micropigmentacion de labios
OK: Cejas y pestañas| 4ever brows | depilación y sombreado castilla
Duplicado: Ortoclin Sede Castilla
OK: Pestañas BA.
OK: Estetica Dental Jessica Orozco
OK: CLASSY GLAM spa de uñas y pestañas
OK: Women studio
OK: Miradas Encantadas
OK: Moldearte centro estético
OK: Imel'd
OK: Estefanía Pérez | Cosmetología y Estética Integral
OK: Milagros spa de uñas
Duplicado: Vital Stetic IPS I Plasma Rico en Plaquetas I Depilación Láser I Cuidado facial y corporal I Suero Terapia
OK: Capil France Salón de Belleza y Barbería
OK: Paula sala de Belleza
OK: BELLEZA Y ESTILO
OK: Salon de belleza luchita
OK: Katy studio
OK: Sala de belleza Jenny
OK: Spa de Uñas
OK: Odontologia Estetica Denty Max
OK: Jhona nails
OK: DCL Estética & Belleza
OK: VIDA SANA 7
OK: MZ Studio
Duplicado: Savia
OK: Veronica cejas,pestañas y lisos orgánico
OK: Sala de belleza cexi
OK: DE angeles nails
OK: Johanarubio_nails
Duplicado: SALUD ORAL CENTER I.P.S S.A.S
OK: Salon de belleza la 97
OK: Consultorio odontológico Andrea hincapie
OK: ROSA - PELUQUERÍA
OK: Nicoletta nails
OK: Florida Parque Comercial
OK: SPA LLERAS
OK: Sienna Salón
OK: Cabellos Y Uñas
OK: Sala de Belleza Splandor

Buscando: clinicas estetica Buenos Aires Medellin
Duplicado: Massai Clínica - Clínica Estética en Medellín
Duplicado: Bonanova Medicina Estética y Bienestar
Duplicado: Dra Monica Pineda | MP Medical Center
Duplicado: Dra. Stephania Pastrana - Medicina Estética

,Nombre,Direccion,Telefono,Web,Rating,Email,Zona,place_id,WhatsApp,Comuna,Categoria,Subcategoria
0,Oral Center Poblado,"Calle 7 # 39- 197, Torre Intermédica Local 121...",(604) 3493080,http://oralcenter.com.co/,4.4,NaN,centros odontologicos El Poblado Medellin,ChIJX2o-xYGCRo4Rn6L7wacsRJo,NaN,Comuna 14 - El Poblado,Salud,Odontologia
1,Dental Center,"Cl. 11 #21, El Poblado, Medellín, El Poblado, ...",(604) 2686922,http://www.dentalcenter.com.co/,4.9,Pacientesdc@gmail.com,centros odontologicos El Poblado Medellin,ChIJgwmJfiYoRI4RvO8goH3oe7M,NaN,Comuna 14 - El Poblado,Salud,Odontologia
2,Centro odontológico KMO Smile Especialistas,"Av. El Poblado #cl 7 39-290, El Poblado, Medel...",314 6628875,NaN,4.9,NaN,centros odontologicos El Poblado Medellin,ChIJc8AO2KUpRI4R5lZzeBklf3U,573146628875.0,Comuna 14 - El Poblado,Salud,Odontologia
3,Poblado Dental,"Cl 10 #42-45 Oficina 229, El Poblado, Medellín...",324 6027040,https://pobladodental.com/,4.6,pobladodental@gmail.com,centros odontologicos El Poblado Medellin,ChIJ42xK_4kpRI4RwY-W14dE_BU,573246027040.0,Comuna 14 - El Poblado,Salud,Odontologia
4,Odontología el Poblado - Oral 10 - Diseños de ...,"Cra. 48 #7 270, El Poblado, Medellín, El Pobla...",301 1795872,http://www.oral10odontologia.com/,5.0,oral10vegas@gmail.com,centros odontologicos El Poblado Medellin,ChIJN3fIPZ8pRI4RytlAMwH5Zuw,573011795872.0,Comuna 14 - El Poblado,Salud,Odontologia
...,...,...,...,...,...,...,...,...,...,...,...,...
1403,Carolina Nail's Spa,"Cr 52 cl 97#125 50003, Medellín, Antioquia, Co...",320 5260389,,,,clinicas estetica Santa Cruz Medellin,ChIJk7AeNtMvRI4RVB4O4g5GkvM,+573205260389,Comuna 2 - Santa Cruz,Estetica,Clinica Estetica
1404,steps,"Cl. 99 #49c47, Santa Cruz, Medellín, Santa Cru...",312 2385215,,,,clinicas estetica Santa Cruz Medellin,ChIJs1R3nd0vRI4R6tp8QdrWof8,+573122385215,Comuna 2 - Santa Cruz,Estetica,Clinica Estetica
1405,Whithe natural odontología integral,"Cl. 98 #51A - 82, La Rosa, Medellín, Santa Cru...",315 0001021,,5,,clinicas estetica Santa Cruz Medellin,ChIJn-HJEHgvRI4R9RIwbudRV2w,+573150001021,Comuna 2 - Santa Cruz,Estetica,Clinica Estetica
1406,Lux Nails,"Cl. 95 #52 -38, Aranjuez, Medellín, Aranjuez, ...",321 8848306,https://linktr.ee/luxnailsmde,,,clinicas estetica Santa Cruz Medellin,ChIJz8PlAAApRI4RoH_5TdZm4-w,+573218848306,Comuna 2 - Santa Cruz,Estetica,Clinica Estetica
1407,glow rose lashes,"Cra. 49 #10399, Moscu I, Medellín, Santa Cruz,...",,,,,clinicas estetica Santa Cruz Medellin,ChIJoXWaqJovRI4R29PyjFRbk2k,,Comuna 2 - Santa Cruz,Estetica,Clinica Estetica

In [ ]:
import requests
import pandas as pd
import re

df = pd.read_excel("leads_medellin_completo.xlsx")

# Filtrar solo estetica sin email
sin_email = df[(df["Subcategoria"] == "Clinica Estetica") & (df["Email"].isna() | (df["Email"] == ""))]
print(f"Registros de estetica sin email: {len(sin_email)}")

def extraer_email_profundo(url):
    if not url or pd.isna(url):
        return ""
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=8)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', response.text)
        emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example', 'jquery'])]
        if emails:
            return emails[0]
        
        from urllib.parse import urljoin
        paginas = [
            urljoin(url, "/contacto"),
            urljoin(url, "/contact"),
            urljoin(url, "/nosotros"),
            urljoin(url, "/about"),
            urljoin(url, "/contactenos"),
        ]
        for pagina in paginas:
            try:
                r = requests.get(pagina, headers=headers, timeout=6)
                if r.status_code == 200:
                    emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', r.text)
                    emails = [e for e in emails if not any(x in e for x in ['sentry', 'wix', 'google', 'schema', 'example', 'jquery'])]
                    if emails:
                        return emails[0]
            except:
                continue
        return ""
    except:
        return ""

for i, row in sin_email.iterrows():
    email = extraer_email_profundo(row.get("Web"))
    if email:
        df.at[i, "Email"] = email
        print(f"OK: {row['Nombre']} --> {email}")
    else:
        print(f"sin email: {row['Nombre']}")

df.to_excel("leads_medellin_completo.xlsx", index=False)
total_estetica = df[df["Subcategoria"] == "Clinica Estetica"]
print(f"\nEmails estetica: {total_estetica['Email'].ne('').sum()} de {len(total_estetica)}")

Registros de estetica sin email: 787
sin email: Wellnes Spa by Clínica Antienvejecimiento, spa Medellín, spa parejas, spa poblado, clínica estética, revitalización facial
sin email: Massai Clínica - Clínica Estética en Medellín
sin email: Clínica Especialistas del Poblado
sin email: EVOLVE Clínica Estética
sin email: Brassia Estética Poblado
sin email: Bonanova Medicina Estética y Bienestar
sin email: Centro Médico Femo Estética - Medellín Poblado
sin email: Dra Monica Pineda | MP Medical Center
sin email: Spa Médica - Dr. Juan Mario Escobar
sin email: Siempreviva Medicina Estética Medellín Poblado
sin email: Alviva Clínica Estética
sin email: Dra. Yulieth Figueroa
sin email: Dra Amy Barreto - Blefaroplastia Abdominoplastia Liposucción Mastopexia Lifting facial Labioplastia Lipoma Cirugía Varices
sin email: Cirugía Estética Avanzada - Cirugia Plastica
sin email: Anay Clínica Estética
sin email: Satori IPS Medicina Estética
sin email: Dr. Yesid Cardenas
sin email: Dr. Milton Rincón Carranza
sin email: Dra. Miralba Montoya | Medicina Estética
sin email: Glam Beauty Bar
sin email: Glow Up Center
sin email: Clínica Medellín Sede El Poblado
sin email: Centro de Estética & Spa Yaneth Sibaja
sin email: Dashka Salon
sin email: Dr Alvaro Correa Jaramillo. Experto en Rinoplastia y Rejuvenecimiento Facial
sin email: Spa Estética Facial
sin email: Massage spa in medellín /Vita Therapy Medellín
sin email: Santa María Estética
sin email: IQ InterQuirófanos - Torre Médical
sin email: Eclat Provenza SPA
sin email: Brassia Estética Laureles
sin email: Clínica Laser
sin email: Skin Centro Estético
sin email: CyE Centro de estética - spa
sin email: BELLEZA LAURELES
sin email: Centro de Estética Gloria López
sin email: Dra. Alejandra Restrepo - Medicina Estética
sin email: Monica Arboleda Centro Estético
sin email: CLINIQ DERMOESTÉTICA Y LÁSER S.A
OK: Centro de estética HSN --> informes@fundacionnosotros.org.ar
sin email: Silumed Medicina Estética
sin email: IM CLÍNIC
sin email: Saestheticspamedellin
sin email: Depilarte Laureles
sin email: DermaFeeling Spa
sin email: 5.0 🌟 Depilación laser hair removal Medellín Dulce Vanidad Centro Estético
sin email: Santorinni
sin email: Centro Estética Manzana Verde
sin email: Happy Nails & Spa Sede Laureles - Medellín
sin email: BELLEZA Y ARMONIA
sin email: Donna Reyther Esthetic Center
sin email: Black & White Medicina Estética Integral
sin email: Estética y Belleza IPS
sin email: Dr. Andrés Duque, medicina estética
sin email: Spa de uñas | Lilah Nails | Manicure y pedicure en laureles
sin email: Aleia Centro de Bienestar
sin email: BODYBRITE LAURELES
sin email: SAVI CENTRO DE ESTÉTICA INTEGRAL
sin email: Maria camila alvarez medicina estética integral
sin email: Centro de estética y bienestar Candamil
sin email: HIDROLIPOCLASIA MEDELLIN
sin email: Alanjara Centro de Belleza y Estética
sin email: Freya Centro Estético
sin email: Centro Médico Femo Estética
sin email: Centro de estética Angelus
sin email: Selem centro estético
sin email: Bukuri Centro Médico y estético
sin email: Luisa Correa Estética
sin email: Centro de Belleza Juliana Ruiz
sin email: Uparela's Studio de Cejas
sin email: Linda Piel Laser Center
sin email: Odontologia Isabella Jaramillo estética dental y funcional
sin email: DRA YESICA GOMEZ
sin email: Bonitas spa de belleza
sin email: Estetica Maria Camila Envigado
sin email: Centro Estético Wendy de la Hoz
sin email: Clínica Nova
sin email: NURA Clínica de Belleza
sin email: Jlassbelleza
OK: Doctor Samuel Restrepo|Imagen Perfecta|Medicina Antienvejecimiento|Limpieza Facial Profunda|Botox|Rejuvenecimiento Facial| --> support@wikommail.com
sin email: Vida cosmetologia y estética
sin email: Nudela Clinic | Centro De Estética
sin email: Miss Divina Center
sin email: Cliniestetica
sin email: INNOSTETIC S.A.S
sin email: Dra. Ana María Restrepo Hernández - Medicina General
sin email: Siempre Bella Envigado
sin email: NC Estilista
sin email: Ungla Centro de Belleza
sin email: Tu Belleza Armonica
sin email: Ela Centro Estético
sin email: Bluma Studio/Cejas-Balayage-Alisados Envigado
OK: My Medical Clinic --> atencionalcliente@colombiavivesalud.com
sin email: Bela Centro De Estética
sin email: CHALO Estilista Profesional
sin email: LQ Essential Spa
sin email: Castaño Láser y Estética
sin email: CLINICA ACTIVECARE SAS
sin email: Eternal Beauty Centro de Cosmetología Y Estética Integral
sin email: QUEEN BEAUTY C.C. CITY PLAZA envigado - Extensiones de pestañas - Micropigmentación - Spa de Uñas - Cuidado Facial y Corporal
sin email: Atenaz woman salón de belleza - envigado
sin email: Consultorio de Medicina Estética, Antienvejecimiento Dr Jorge Porras
sin email: Lorena Orjuela Estética Integral
sin email: Spa Armonía y Belleza con Estilo
OK: Palacio de la Keratina envigado --> ejemplo@dominio.com
sin email: Nathivas spa
sin email: Otus Spa
sin email: Pao Rojas Studio
sin email: Cristina Sierra VIP - Envigado
sin email: Solo Cejas Envigado Parque
sin email: Sala Belleza Envigado - Catalina Uribe Profesionales Belleza
sin email: Grupo Estético Elixir
sin email: Dra. Paulina Tirado
sin email: Depilarte Viva Envigado
sin email: Miss Cejas Spa Envigado
sin email: Centro Estético Leidy Londoño
sin email: Estudio de Belleza Neyda Camacho
sin email: Centro de Estética Yerbabuena
sin email: Soler Envigado - Centro de Bronceo y Rejuvenecimiento High Tech
sin email: Odontología Estética Especializada Envigado Victor A. Sossa Pérez
sin email: Uñas & glamour
sin email: Centro Salud & Belleza Bello
sin email: Centro Estetico y Cosmetologico Del Norte
sin email: Bello spa
sin email: KA Esthetic Salud y Belleza
sin email: ICONO SPA ★
sin email: Estética Sara pino
sin email: Enjoy estética- spa
sin email: ALISADOS EN BELLO | RESTAURACIÓN CAPILAR EN BELLO | TINTE DE CABELLO EN BELLO
sin email: Victoria Beauty
sin email: Mundo Pestañas Spa
sin email: Centro Estetico Tendencias y Estilo
sin email: Aquiub Casa de Pestañas Bello
sin email: Belle Peau | Centro de Medicina Estética en Bello
sin email: Depilarte Bello
sin email: Be Live Centro de Estética
sin email: Eliana Arévalo Spa
sin email: Centro De Belleza Integral Angeles Bellos
sin email: Acuarela Belleza y Salud - Parque Fabricato
OK: Natural Fashion Bello - Expertos en Micropigmentación --> citas@naturalfashion.com.co
sin email: PLATINUM Centro de Belleza
sin email: BOGA Centro Integral De Belleza
sin email: KG Nails and Beauty
sin email: vanessa rios-cosmetologa -bello micropigmentación
sin email: DiansClinic
sin email: Di Bell Nails Spa En Bello
sin email: Spa Maria Bonita
sin email: Super Mechas
sin email: Bloom centro estético
OK: Colegiatura Antioqueña de Belleza --> admisiones@lacole.edu.co
sin email: Lovelly Spa - Estetica Integral
sin email: MOKA SPA
sin email: ASIA V.I.P UÑAS Y CABELLO
sin email: Benditas Spa
sin email: VISAGO BELLEZA Y SALUD
sin email: Bello Beauty Bar
sin email: Luisa Sierra Estética Integral
sin email: Nilly Belleza y Bienestar
sin email: Isabel Vélez Estética
sin email: Ataraxia Spa de Uñas y Cejas
sin email: Angel skin estetica
sin email: Dahia Keratin - Sede Bello
sin email: Cuerpo Ideal Estética Sede Bello
sin email: Yesica Moreno Centro de alisados Bello
sin email: Spa de uñas en Bello Angy Ciro Nails
sin email: Depilarte Fabricato
sin email: Le Petit Salón
sin email: Spa De Uñas En Bello Santísima
sin email: Lym centro de belleza
sin email: Vanessa Pulgarin Nails
sin email: GlowLash Spa Cejas Y Pestañas .
sin email: Magical SPA
sin email: Milagros Spa
sin email: Centro De Belleza Jenny
sin email: Aval Spa & Esthetic
sin email: Estética Facial By Alejandra Arias
sin email: Buon Corpo Estética
sin email: Centro estético Laura Melisa
sin email: ELITE CENTRO ESTÉTICO
sin email: YM Beauty Studio
sin email: Alquimia spa itagui
sin email: Magic Beauty Spa
sin email: Only Her Studio
sin email: Medicina Estética Dr Javier Velez
sin email: Báltica estética micropigmentación
sin email: COQUETAS SPA ITAGUI
sin email: Trilogía Spa
sin email: monaco nails spa
sin email: Experiencia Esvera
sin email: Acqua Color Spa
sin email: Cómo tú spa
sin email: Real Casa de Alisados y Depilación Itagüí
sin email: Sofia Naranjo Nails
sin email: Estudio de Belleza - Kathe Rivera
sin email: Lashesbykateb
sin email: Centro Estético Leidy Barrera
sin email: Luna spa
sin email: HADASSAH cejas & pestañas
sin email: Secret spa de uñas
sin email: Implestetica
sin email: Natalia Giraldo Salón Sede Itagüi
sin email: Centro de Belleza Color Tech
sin email: Estética Sandra Giraldo
sin email: Esteticas janeth sede itagui
sin email: Amarantha Beauty SPA
sin email: Luzete Salon
sin email: Bendito Naturals
sin email: KAIROS PIERCING
sin email: Tropical Nails Spa / Spa de uñas
sin email: Profesional Cejas
sin email: Figura y Sonrisas
sin email: Pigment Pro
sin email: Rómez Estética Integral
sin email: Estética integral MS
sin email: Yasmin Gaviria Especialista en Micropigmentación
sin email: Meraki Sala de Belleza, spa de uñas y Barbería
sin email: Melissa Alvarez Especialista en cejas y pestañas
sin email: Spa Nails marianne
sin email: Tarot spa
sin email: Arisha spa
sin email: Andreina nails spa
sin email: Rebecca nails spa
OK: Mantras Estetica --> informes@fundacionnosotros.org.ar
sin email: Serena estudio de belleza
sin email: MP-SPA
sin email: PIES PERFECTOS CUIDADO ESPECIALIZADO
sin email: Centro estético FB
sin email: Solo Cejas - Barrio la independencia
sin email: Exóticas Spa
sin email: Clínica de Estética - Centro de Belleza - Céu Te Cuida CC Molinos
sin email: Dra. Stephania Pastrana - Medicina Estética
sin email: PRANA Clinic
sin email: Dra. Adriana Diaz - Estética Medica
sin email: GEA Lipo Sin Cirugía Medellín
sin email: Almaluna Centro Estético
sin email: Nativa Medicina Estética
sin email: Centro de Estética Spa Bolivia
sin email: ORU MEDICINA ESTETICA
sin email: Odamed Centro de Estética y Salud
sin email: María Eunice Betancourt - Medicina Estética
sin email: Béleco Medicina Estética
sin email: Saudé Genuina | Medicina Funcional y Estética en Medellin
sin email: Clínica Bella Vie | Cirugía Plástica y Estética en Medellín
sin email: Centro De Estética | Céu Te Cuida | C.C. El Tesoro
sin email: Clinica de cejas
OK: Savia --> contacto@saviamedicinaestetica.com.co
sin email: Anama Clinic | Medicina Estética
sin email: Medicina estética Karin
sin email: Borage Concept Studio
sin email: Sofia Muñoz Esthetic Center & Spa
sin email: Cerarte Spa
sin email: Creative Colors Salón
sin email: casa canela spa
sin email: Centro de Estética y Belleza Bella Mia S.A.S.
sin email: Paraíso Spa
sin email: Almas Centro Estético
sin email: Serenity Spa
sin email: Aquiub Casa de Pestañas Sabaneta
sin email: Athena Estudio de Belleza
sin email: ConforPiel
sin email: Amaspa
sin email: Cejas y estética by Andrea Ramirez
sin email: Valentina Echavarría Centro de belleza
sin email: MG Pestañas - Sabaneta
OK: Limaica Studio-Depilacion con láser/cera. --> Idarragalina88@gmail.com
sin email: Centro De Estética | Céu Te Cuida | C.C. Mayorca
sin email: ISANIA beauty house
sin email: J&T Centro de Acondicionamiento Estético
sin email: Glow Beauty Bar
sin email: Mirella Acosta Spa and Stetic
sin email: BM Spa de Uñas y Estética
OK: Toques de Belleza --> vue@2.6.14.js
sin email: Matiz Salud y Belleza
sin email: Lola Nails Spa
sin email: centro estetico Luxury Beauty
sin email: Vive Salon Beauty
sin email: Centro De Estetica Lulu
sin email: CH BEAUTY SALON SABANETA
sin email: Solo Cejas - Sabaneta parque
sin email: Centro De Belleza Amoret
sin email: Sandra Olarte SPA
sin email: Depilarte Sabaneta
sin email: Vital Masoterapia
sin email: Sky Beauty Spa Colombia
sin email: Mariana Álvarez Beauty
sin email: Pielez centro estético
sin email: CENTRO DE ESTETICA ZACHA
sin email: Spa Look violetts
sin email: ODONTOLOGÍA AURA MARÍA
sin email: ESSENS HAIR SALON & BARBERSHOP
sin email: Dra. Paula Ànama
sin email: Embell Studio -Sabaneta
sin email: Acuarela Belleza y Salud - Aves María
sin email: Bloomy spa
sin email: Lienzo SPA Uñas y Belleza – Sabaneta, Antioquia
sin email: Elite Beauty spa
sin email: Valeria Restrepo Z centro de estética
sin email: Malibú Centro Estético
sin email: Figurbell spa Reduce medidas de abdomen sin cirugias
sin email: Belén Estética
sin email: Be Beauty by Valentina.
sin email: Olgys Cejas
sin email: Centro Estético Integral Rosales
sin email: clinica del cabello
sin email: CELESTIAL TIENDA DE BELLEZA
sin email: Sublime sala de belleza
sin email: lashesbytatigiraldo
sin email: Marosa Nails Spa
sin email: The Heaven
sin email: Spa Luna M
sin email: Zahara Estética y Spa
sin email: Calma centro de bienestar y estética integral
sin email: Spa Divinas Nails
sin email: FASHION NAILS MED
sin email: Vital Stetic IPS I Plasma Rico en Plaquetas I Depilación Láser I Cuidado facial y corporal I Suero Terapia
sin email: Centro Estetico en Medellin - Unica Centro Estetico
sin email: CENTRO ESTÉTICO D'ANGEL- Local 231
sin email: Eterna Studio Robledo
sin email: Concept Nails
sin email: Solo Cejas - Robledo
sin email: Encantadas cejas & pestañas
sin email: Amatsu Spa - Masajes y Spa en Medellín
sin email: Dulce Figura Spa - Masajes Reductores & Relajantes Medellín
sin email: Beauty Variedades
sin email: Dr. Andrés Álvarez
OK: Viva Spa --> info@vivaspamedellin.com
sin email: Mas Bella
sin email: Maryo beauty
sin email: Pestañas Sensación
sin email: Éxito Robledo
sin email: Sala de Belleza Unisex
sin email: Parque Robledo
sin email: Emunah Belleza Sobrenatural
sin email: Samy nails manicurista
sin email: Robledo bello horizonte
sin email: Mercy Nails
sin email: Angela Nails spa
sin email: Consultorio Odontologico Dr. Oscar Velásquez
sin email: Centro Integral Salud y Belleza
sin email: Angie
sin email: Centro Spa Castilla- Estetica Adri's
sin email: Adahlia Spa
sin email: Nice centro de belleza
sin email: BIP PROFESIONAL - Artistas en Belleza
sin email: Paulinails Sede Castilla
sin email: Mimosas Spa
sin email: MORETTA CENTRO ESTÉTICO
sin email: Daniela Henao
sin email: Divinas Medellin
sin email: Sala de Belleza Doral
sin email: Dlaser Medellin
sin email: Divas Spa
sin email: Salón Dahian's
sin email: Bellísimas beuty spa
sin email: LA CASITA D' LAS UÑAS
sin email: MADRID SPA CEJAS Y PESTAÑAS
sin email: Irinna spa
sin email: Solo Cejas - Castilla
sin email: Sara Nails
sin email: Sueños Nails Spa
sin email: Pestañas pelo a pelo y Micropigmentacion de labios
sin email: Cejas y pestañas| 4ever brows | depilación y sombreado castilla
sin email: Pestañas BA.
sin email: Estetica Dental Jessica Orozco
sin email: CLASSY GLAM spa de uñas y pestañas
sin email: Women studio
sin email: Miradas Encantadas
sin email: Moldearte centro estético
sin email: Imel'd
sin email: Estefanía Pérez | Cosmetología y Estética Integral
sin email: Milagros spa de uñas
sin email: Capil France Salón de Belleza y Barbería
sin email: Paula sala de Belleza
sin email: BELLEZA Y ESTILO
sin email: Salon de belleza luchita
sin email: Katy studio
sin email: Sala de belleza Jenny
sin email: Spa de Uñas
sin email: Odontologia Estetica Denty Max
sin email: Jhona nails
sin email: DCL Estética & Belleza
sin email: VIDA SANA 7
sin email: MZ Studio
sin email: Veronica cejas,pestañas y lisos orgánico
sin email: Sala de belleza cexi
sin email: DE angeles nails
sin email: Johanarubio_nails
sin email: Salon de belleza la 97
sin email: Consultorio odontológico Andrea hincapie
sin email: ROSA - PELUQUERÍA
sin email: Nicoletta nails
sin email: Florida Parque Comercial
sin email: SPA LLERAS
sin email: Sienna Salón
sin email: Cabellos Y Uñas
sin email: Sala de Belleza Splandor
sin email: Dr. Camilo Torres Medicina Estética
sin email: CAIRO STUDIO
sin email: Maph nails spa
sin email: Skin Clinic - The Esthetic Center & Bronze
sin email: Dgloss
sin email: DR CARLOS CERVANTES
sin email: ESBELTA SPA CENTRO ESTETICO
sin email: Magica Spa uñas
sin email: Alexa Centro de Estetica - Spa Medellín
sin email: Sarame Spa
sin email: Love your skin
sin email: Mi Secreto Spa
sin email: Perfect Nails Anm
sin email: Turkista Piel
sin email: Sophi Nails a Domicilio.
sin email: JC Belleza cosmética y capilar
sin email: mile.cuidados
sin email: Camilo Montoya Studio.Estilista y Maquillador Profesional
sin email: Valentina villa nails
sin email: Natycorreanails
sin email: Dra. Estefanía Pineda Álvarez
sin email: Miradas místicas 2
sin email: Sala de belleza MyLuR
sin email: Elena Spa
sin email: d' Caché La 42
sin email: Susana Ramírez Nails Spa
sin email: Joselinne. Estilo en uñas
sin email: SALON DE BELLEZA Y BARBERIA UBIELLYS
sin email: SUPERNOVA STUDIO
sin email: Feet Nails
sin email: Vitaléa
sin email: DAY ENCANTO SPA
sin email: Vivianalunaesteticaintegral
sin email: Bella con Elegancia
sin email: Lisos Perfectos
sin email: SPA A'G nails.arte
sin email: Isabel Murillo sala de Belleza
sin email: Spa y Estetica Shalom
sin email: MedeDreadlocks (Medellín)
sin email: Susy Spa
sin email: Mantra nails spa
sin email: Uñas Lindas Medellín - NailsByWeen - SHOP NAILS
sin email: El Tocador De Vale
sin email: Solo Cejas - Manrique
sin email: Suprema mujer spa
sin email: Sara Molina Brows
sin email: Cejas y pestañas | 4ever brows | depilación y sombreado Manrique
sin email: El Palacio De Las Cejas
sin email: Daniela cano nails and lashes
sin email: Karol_Nails_Spa
sin email: Valentina nails
sin email: CELESTIK
sin email: SPA VIDA ZEN
sin email: Estéticas Janeth
sin email: Yenifervargas.hairymakeup
sin email: Sara Rodríguez Cosmetología & Estética
sin email: GlowStudio
sin email: CATALINA DAVILA NAILS SPA
sin email: Bellisimas Spa
sin email: Trenzas Africanas- Domicilios
sin email: Milán Nails Spa
sin email: Mia Bliss Spa
sin email: Saraycano_ princess
sin email: Sala de belleza Zoe in
sin email: Verdementaspa by Sara T
sin email: centro de estetica piel de jazmines
sin email: Marayah Spa - cejas y pestañas
sin email: Torre Médica El Tesoro
sin email: Magic lashes
sin email: Lorena zapata studio
sin email: UÑAS FAMOSAS SPA
sin email: PROFESSIONAL NAIL'S by Vanessa Silva
sin email: Odontología integral estética Álvaro Hernández
sin email: Jc Insumos
sin email: Juan karLOOk's
sin email: Paula Barrientos expresión en tu mirada
sin email: JM estilo y belleza
sin email: NOVADERMIS
sin email: keratinas Epa Colombia Katalina Palacio salon
sin email: VIOLETAS NAILS SPA PELUQUERÍA
sin email: GabrielaSalcedoSpa
sin email: Centro de Estética Natural Body
sin email: Centro de belleza Shannel, Aranjuez
sin email: Nuo Spa
sin email: Amelia Nail Spa
sin email: Spa Luna M
sin email: Imperio Nails Spa
sin email: San Angel Stetic
sin email: Solo Cejas- Aranjuez
sin email: Dra Maria Carolina Montoya
sin email: Mundo Belleza Colombia
sin email: Equilibrium Estética & Bienestar
sin email: Bella estética Copacabana.
sin email: IBC Integral Beauty Center
sin email: Heidy Guarin Salon
sin email: Centro Clínico Estético Mario Arango
sin email: Ikigai
sin email: Ganesha Nails Spa
sin email: Centro de Estética Copacabana
sin email: Decouñas
sin email: Eminails
sin email: Sara Laverde maquillaje, peinado y depilación de cejas
sin email: Ámate Centro Estético
sin email: Drenagem Linfática em Copacabana - Massoterapia e Estética em Copacabana Aline Bárbara
sin email: D'Marxi Spa
sin email: Yo Amo Mis Rizos Naty Echavarría
sin email: Dra. Maria Toro
sin email: Maca Nail's Spa
sin email: Sweet Nails & Spa
sin email: ESTETICA | CENFICOP | CENTRO DE FISIOTERAPIA
sin email: Casa del Cabello
sin email: Spa Nelly Jaramillo
sin email: Salón de Belleza Divina Vanidad
sin email: Iluminos Odontología Estética
sin email: Gracia Divina Lash Studio
sin email: Vivalylash belleza integral
sin email: Estúdio Estética Copacabana
sin email: Nefertiti centro de belleza integral
sin email: KEYLA GONZALEZ NAILS SPA
sin email: Alma Bella
sin email: Centro de Atención y Bienestar Integral
sin email: Estudio GAIA
sin email: CABI COPACABANA
sin email: Dkhenaomakeupstudio
sin email: Liliana Taborda cosmetologa
sin email: Majo Castillo Studio
sin email: Sabai spa
sin email: LADY PEREZ ESTÉTICA SPA

In [ ]:
import pandas as pd

df = pd.read_excel("leads_medellin_completo.xlsx")
estetica = df[df["Subcategoria"] == "Clinica Estetica"]
print(f"Total estetica: {len(estetica)}")
print(f"Con email: {estetica['Email'].ne('').sum()}")
print(f"Con WhatsApp: {estetica['WhatsApp'].ne('').sum()}")
print(f"Con Web: {estetica['Web'].ne('').sum()}")

In [1]:
import pandas as pd

df = pd.read_excel("leads_medellin_completo.xlsx")
estetica = df[df["Subcategoria"] == "Clinica Estetica"]
print(f"Total estetica: {len(estetica)}")
print(f"Con email: {estetica['Email'].ne('').sum()}")
print(f"Con WhatsApp: {estetica['WhatsApp'].ne('').sum()}")
print(f"Con Web: {estetica['Web'].ne('').sum()}")

Total estetica: 891
Con email: 891
Con WhatsApp: 891
Con Web: 891

In [2]:
import pandas as pd

df = pd.read_excel("leads_medellin_completo.xlsx")
estetica = df[df["Subcategoria"] == "Clinica Estetica"]

print(f"Total estetica: {len(estetica)}")
print(f"Con email: {estetica['Email'].notna().sum()}")
print(f"Sin email: {estetica['Email'].isna().sum()}")
print(f"Email vacio: {(estetica['Email'] == '').sum()}")
print(f"Con WhatsApp: {estetica['WhatsApp'].notna().sum()}")
print(f"Sin WhatsApp: {estetica['WhatsApp'].isna().sum()}")

Total estetica: 891
Con email: 104
Sin email: 787
Email vacio: 0
Con WhatsApp: 722
Sin WhatsApp: 169

In [1]:
import pandas as pd
import re
import time
import random
from urllib.parse import urljoin

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import WebDriverException
from webdriver_manager.chrome import ChromeDriverManager

# ── CONFIGURACIÓN ──────────────────────────────────────────────
ARCHIVO = "leads_medellin_completo.xlsx"
PAUSA_MIN = 3
PAUSA_MAX = 7

def crear_driver():
    options = Options()
    options.add_argument("--headless")               # sin ventana
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1920,1080")
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
    options.add_argument("--log-level=3")            # silencia logs de Chrome
    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=options
    )
    driver.set_page_load_timeout(15)
    return driver

FILTROS_EMAIL = ['sentry', 'wix', 'google', 'schema', 'example', 'jquery',
                 'png', 'jpg', 'svg', 'css', 'js', '@2x', 'webpack']

def extraer_emails_de_html(html):
    emails = re.findall(r'[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}', html)
    return [e for e in emails if not any(x in e.lower() for x in FILTROS_EMAIL)]

def extraer_email_selenium(driver, url):
    if not url or pd.isna(url):
        return ""

    paginas = [
        url,
        urljoin(url, "/contacto"),
        urljoin(url, "/contact"),
        urljoin(url, "/nosotros"),
        urljoin(url, "/about"),
        urljoin(url, "/contactenos"),
    ]

    for pagina in paginas:
        try:
            driver.get(pagina)
            time.sleep(2)  # espera a que cargue el JS

            # Busca en el HTML renderizado
            html = driver.page_source
            emails = extraer_emails_de_html(html)
            if emails:
                return emails[0]

            # También busca en mailto: links (más confiable)
            mailto_links = driver.find_elements("css selector", "a[href^='mailto:']")
            for link in mailto_links:
                href = link.get_attribute("href")
                if href:
                    email = href.replace("mailto:", "").split("?")[0].strip()
                    if email and "@" in email:
                        return email

        except WebDriverException:
            continue
        except Exception:
            continue

    return ""

# ── MAIN ───────────────────────────────────────────────────────
df = pd.read_excel(ARCHIVO)

sin_email = df[
    (df["Subcategoria"] == "Clinica Estetica") &
    (df["Email"].isna() | (df["Email"] == ""))
]
print(f"Clínicas estética sin email: {len(sin_email)}")
print("Iniciando Selenium...\n")

driver = crear_driver()
encontrados = 0

try:
    for i, row in sin_email.iterrows():
        email = extraer_email_selenium(driver, row.get("Web"))

        if email:
            df.at[i, "Email"] = email
            encontrados += 1
            print(f"✅ {row['Nombre']} --> {email}")
        else:
            print(f"❌ sin email: {row['Nombre']}")

        # Guarda cada 10 registros por si se interrumpe
        if encontrados % 10 == 0 and encontrados > 0:
            df.to_excel(ARCHIVO, index=False)
            print(f"   💾 Guardado parcial ({encontrados} emails nuevos)")

        time.sleep(random.uniform(PAUSA_MIN, PAUSA_MAX))

finally:
    driver.quit()
    df.to_excel(ARCHIVO, index=False)
    df.to_excel(ARCHIVO, index=False)

total_estetica = df[df["Subcategoria"] == "Clinica Estetica"]
print(f"Emails estética: {total_estetica['Email'].ne('').sum()} de {len(total_estetica)}")
print(f"Emails nuevos encontrados esta sesión: {encontrados}")

ModuleNotFoundError: No module named 'selenium'

In [ ]:
import pandas as pd
import re
import time
import random
from urllib.parse import urljoin

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import WebDriverException
from webdriver_manager.chrome import ChromeDriverManager

ARCHIVO     = "leads_medellin_completo.xlsx"
ARCHIVO_OUT = "leads_medellin_actualizado.xlsx"  # guarda aquí, no toca el original
PAUSA_MIN   = 3
PAUSA_MAX   = 7

def crear_driver():
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1920,1080")
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
    options.add_argument("--log-level=3")
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    driver.set_page_load_timeout(15)
    return driver

FILTROS_EMAIL = ['sentry', 'wix', 'google', 'schema', 'example', 'jquery',
                 'png', 'jpg', 'svg', 'css', 'js', '@2x', 'webpack']

def extraer_emails_de_html(html):
    emails = re.findall(r'[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}', html)
    return [e for e in emails if not any(x in e.lower() for x in FILTROS_EMAIL)]

def extraer_email_selenium(driver, url):
    if not url or pd.isna(url):
        return ""
    for slug in ["", "/contacto", "/contact", "/nosotros", "/about", "/contactenos"]:
        try:
            driver.get(urljoin(url, slug) if slug else url)
            time.sleep(2)
            emails = extraer_emails_de_html(driver.page_source)
            if emails:
                return emails[0]
            for link in driver.find_elements("css selector", "a[href^='mailto:']"):
                href = link.get_attribute("href")
                if href:
                    email = href.replace("mailto:", "").split("?")[0].strip()
                    if email and "@" in email:
                        return email
        except:
            continue
    return ""

df = pd.read_excel(ARCHIVO)

sin_email = df[
    (df["Subcategoria"] == "Clinica Estetica") &
    (df["Email"].isna() | (df["Email"] == ""))
]
print(f"Clínicas estética sin email: {len(sin_email)}")

driver = crear_driver()
encontrados = 0

try:
    for i, row in sin_email.iterrows():
        email = extraer_email_selenium(driver, row.get("Web"))
        if email:
            df.at[i, "Email"] = email
            encontrados += 1
            print(f"✅ {row['Nombre']} --> {email}")
        else:
            print(f"❌ {row['Nombre']}")

        if encontrados > 0 and encontrados % 10 == 0:
            df.to_excel(ARCHIVO_OUT, index=False)
            print(f"   💾 Guardado parcial: {encontrados} emails")

        time.sleep(random.uniform(PAUSA_MIN, PAUSA_MAX))

finally:
    driver.quit()
    df.to_excel(ARCHIVO_OUT, index=False)
    print(f"\n💾 Guardado en: {ARCHIVO_OUT}")

total = df[df["Subcategoria"] == "Clinica Estetica"]
print(f"Emails estética: {total['Email'].notna().sum()} de {len(total)}")
print(f"Emails nuevos esta sesión: {encontrados}")

Clínicas estética sin email: 787
✅ Wellnes Spa by Clínica Antienvejecimiento, spa Medellín, spa parejas, spa poblado, clínica estética, revitalización facial --> servicioalcliente@clinica-antienvejecimiento.com
❌ Massai Clínica - Clínica Estética en Medellín
❌ Clínica Especialistas del Poblado
❌ EVOLVE Clínica Estética

In [7]:
import sys
print(sys.executable)

C:\ProgramData\anaconda3\python.exe

In [8]:
import subprocess
subprocess.run([r"C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\python.exe", 
                "-m", "pip", "install", "selenium", "webdriver-manager"])

CompletedProcess(args=['C:\\Users\\LENOVO\\AppData\\Local\\Programs\\Python\\Python314\\python.exe', '-m', 'pip', 'install', 'selenium', 'webdriver-manager'], returncode=0)

In [9]:
import sys
print(sys.version)

3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]

In [13]:
import subprocess
import sys
subprocess.run([sys.executable, "-m", "pip", "install", "selenium", "webdriver-manager"])

CompletedProcess(args=['C:\\ProgramData\\anaconda3\\python.exe', '-m', 'pip', 'install', 'selenium', 'webdriver-manager'], returncode=0)

In [14]:
import subprocess
import sys
subprocess.run([sys.executable, "-m", "pip", "install", "selenium", "webdriver-manager"], capture_output=False)

CompletedProcess(args=['C:\\ProgramData\\anaconda3\\python.exe', '-m', 'pip', 'install', 'selenium', 'webdriver-manager'], returncode=0)

In [15]:
import selenium
print(selenium.__version__)

4.41.0

In [16]:
import pandas
import requests
import openpyxl
import numpy
import matplotlib
import scipy
import sklearn

paquetes = {
    "pandas": pandas.__version__,
    "requests": requests.__version__,
    "openpyxl": openpyxl.__version__,
    "numpy": numpy.__version__,
    "matplotlib": matplotlib.__version__,
    "scipy": scipy.__version__,
    "sklearn": sklearn.__version__,
}

for p, v in paquetes.items():
    print(f"{p}: {v}")

pandas: 2.2.3
requests: 2.32.3
openpyxl: 3.1.5
numpy: 2.1.3
matplotlib: 3.10.0
scipy: 1.15.3
sklearn: 1.6.1

In [17]:
import pandas
import requests
import openpyxl
import numpy
import matplotlib
import scipy
import sklearn

paquetes = {
    "pandas": pandas.__version__,
    "requests": requests.__version__,
    "openpyxl": openpyxl.__version__,
    "numpy": numpy.__version__,
    "matplotlib": matplotlib.__version__,
    "scipy": scipy.__version__,
    "sklearn": sklearn.__version__,
}

for p, v in paquetes.items():
    print(f"{p}: {v}")

pandas: 2.2.3
requests: 2.32.3
openpyxl: 3.1.5
numpy: 2.1.3
matplotlib: 3.10.0
scipy: 1.15.3
sklearn: 1.6.1

In [18]:
import pandas
import requests
import openpyxl
import numpy
import matplotlib
import scipy
import sklearn

paquetes = {
    "pandas": pandas.__version__,
    "requests": requests.__version__,
    "openpyxl": openpyxl.__version__,
    "numpy": numpy.__version__,
    "matplotlib": matplotlib.__version__,
    "scipy": scipy.__version__,
    "sklearn": sklearn.__version__,
}

for p, v in paquetes.items():
    print(f"{p}: {v}")

pandas: 2.2.3
requests: 2.32.3
openpyxl: 3.1.5
numpy: 2.1.3
matplotlib: 3.10.0
scipy: 1.15.3
sklearn: 1.6.1